#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:de490bc04784650e59b5fdf6eea88fdfcd1b0e9dd07f497af7bd7954e9694467"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:7227711e112271694f464f4954fbdc1096191128ca93ad2b93a0708f587f766c"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-SNAPSHOT
    digest: "sha256:e8404c00126569118e02e440cfea3e472a489165d71d99589bc381391ed9ca89"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:2f271f7d4804aec45e808309a6eb25fb4ddaacf84d2c89d69e2c0a7717c75795"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:62ffe9f06951fa0cb47060e27b8da29f1200f17861e7a800314423d815c8b87f"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:e782a0d8193c07b53ea5e2c85f86d5eaafe8d616232b6a08731fc8e54b8df3f6"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:135eaa4b045868ae864e063883ed5adebbacb5adb213624218621778f769e6b9"
