#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.10-SNAPSHOT
    digest: "sha256:bc30049fadef54f289961198e93b47d495f99a6e225aafb900703cebcd436953"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.10-SNAPSHOT
    digest: "sha256:44616c55d134e48e797b561d85537fe439f0599d9a3fe47f76382b0bbe2bdf69"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.10-SNAPSHOT
    digest: "sha256:a32ee422894c3347861aac418e5fa963a526b394245e009b7e45b1025010e555"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/hub/tags
  restapi:
    image:
      repository: camunda/hub
      tag: SNAPSHOT

  # https://hub.docker.com/r/camunda/hub-websockets/tags
  websockets:
    image:
      repository: camunda/hub-websockets
      tag: SNAPSHOT

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.10-SNAPSHOT
    digest: "sha256:43cbd09c29c77718f07bbb817bb914e918bb32b6f0b6fb8aedfebde3455f5e4e"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:091a28fe30b007986c138b3d975f9425d41273327fcc5bce4949bc41290379c6"
