#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.10-SNAPSHOT
    digest: "sha256:bc30049fadef54f289961198e93b47d495f99a6e225aafb900703cebcd436953"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.10-SNAPSHOT
    digest: "sha256:7ba3d7cec343bb3e4942dcbcfad0cc2806e435eadbd21441d67935faa189b18c"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.10-SNAPSHOT
    digest: "sha256:510cacf5759c29aa41447a2b77899a608112f41a6c95d34429a3509daada782d"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/hub/tags
  restapi:
    image:
      repository: camunda/hub
      tag: SNAPSHOT

  # https://hub.docker.com/r/camunda/hub-websockets/tags
  websockets:
    image:
      repository: camunda/hub-websockets
      tag: SNAPSHOT

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.10-SNAPSHOT
    digest: "sha256:79abb9fa81d62f5410d67df2cf6acd266e1b0027241287a80b3fe70082bb7f91"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:3d6e5fb3a1deeba08fd814dc540bf819a644a5859c95a4eeae251a449d262425"
