{{- if .Values.webModeler.enabled -}}
{{- $usePusherSecret := not (eq "true" (include "camundaPlatform.hasSecretConfig" (dict "config" .Values.webModeler.restapi.pusher))) -}}
{{- $usePusherAppKey := not (eq "true" (include "camundaPlatform.hasSecretConfig" (dict "config" .Values.webModeler.restapi.pusher.client))) -}}
{{- if or $usePusherSecret $usePusherAppKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webModeler.fullname" . }}
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
type: Opaque
data:
  {{- if $usePusherSecret }}
  pusher-app-secret: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
  {{- if $usePusherAppKey }}
  pusher-app-key: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
