#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:6b90311580e1de959a4f2c2527f7ece000588ca9fdcbc810591f9b5571b46241"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8.8
    digest: "sha256:ecc7124ef788de6e1e9756861dd2aa7b7fe9a0a18638a94b769d477c7c166c77"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8.7
    digest: "sha256:54976aec939f3fe49af377e13b6b5f91a1dcaafa252e7cfc90129891c86b6e81"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: 8.8
      digest: "sha256:74d2b59ae48be55eb6e57b1b41fad3d6aaa88922c6142f32f3c350c1543a0634"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: 8.8
      digest: "sha256:03ee280d0f23e760d8fbc018a004cb4d56785afe94fef05aa2e4241ebbb414df"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: 8.8
      digest: "sha256:45ef1b843cefd8874d9d4a36b4e92e7c1e43901b3c40aa02baadc94dae6160b5"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8.15
    digest: "sha256:651769071275b8ace09e4a7f6e7a43122e273055cab4fe33443d2a3d4d356349"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8.9
    digest: "sha256:18aaa5497dc32424b5b56c87c76563845afb7ba39a5a734431aa2cb47ee91424"
