#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:532d06524542f6a6eed504ac4719b6b7ad667d8d71aac1a3f5f5f385e44ffb72"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8.18
    digest: "sha256:bbd43d3ca8773f5151d7ea831dc45b87cfe25130198d60f6dbcbac19ecb2d159"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8.36
    digest: "sha256:c07aeb889f8ce5c09fb92bba650a70855c758a2c6acccded39576086fa6413bc"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: 8.8
      digest: "sha256:1793a8821e38548ea72ea98caa382f1d432beeb53f7dffc3ef7f551416bd27a6"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: 8.8
      digest: "sha256:edb1a9c652d49abf5a959285eff565929bf9584c53238d39fd2bd7faa1737363"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: 8.8
      digest: "sha256:d7abcb9ead1b87d5047cf570290f08f2344d16a372de5417307cf214c00d119c"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8.36
    digest: "sha256:859805fb024b8b276a604ab611dc0a8b80d414a27c76e86b8f5c38e72f06553f"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8.16
    digest: "sha256:191d4fe2e4eaea9651f41596434c8448c5664fc36d3b537db2ed3b2ee9cde3a0"
