#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:532d06524542f6a6eed504ac4719b6b7ad667d8d71aac1a3f5f5f385e44ffb72"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8.21
    digest: "sha256:7763a1d54eea4e9e14ab0ea6dbf87d4056cc5bf71e0ffc7c3ef312a43ec8c56c"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8.39
    digest: "sha256:6d33fea5a9d5a03050d02420f24ea93fbd3340708456747eb57584caf673820d"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: 8.8
      digest: "sha256:04cb0dfc5fcfebfd53ff28e9ddad7e4e54baef41d222e372d1af4656db32506e"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: 8.8
      digest: "sha256:5ad7ccc5ecde43a0f8bcf45fe31010811740421963584fe41d719f512b78b1fd"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: 8.8
      digest: "sha256:c9421bb26441bc4cdd3808779e66bd4471f845d8fcf385d005de1612b2adb38e"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8.39
    digest: "sha256:22d3f80c36915344817c7e43976bc47e6a8767182c919fe7afffc357f6792858"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8.17
    digest: "sha256:c9f67e7ea5a01415000added6ef0d54d03d9dc574c513e26bb97adf790f17057"
