---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-eks-tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: aws-camunda-cloud-tls  # name of the k8s Secret to be created
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: products/distribution/ci/eks-tls
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: products/distribution/ci/eks-tls
      property: tls.key
