---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: camunda-helm-existing-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: distribution-team
  target:
    name: integration-test-credentials  # name of the k8s Secret to be created
    template:
      engineVersion: v2
      data:
        client-secret: '{{ index . "client-secret" }}'
        entra-child-app-client-secret: '{{ index . "entra-child-app-client-secret" }}'
        identity-firstuser-password: '{{ index . "identity-firstuser-password" }}'
        operate-secret: '{{ index . "operate-secret" }}'
        tasklist-secret: '{{ index . "tasklist-secret" }}'
        optimize-secret: '{{ index . "optimize-secret" }}'
        connectors-secret: '{{ index . "connectors-secret" }}'
        console-secret: '{{ index . "console-secret" }}'
        keycloak-secret: '{{ index . "keycloak-secret" }}'
        zeebe-secret: '{{ index . "zeebe-secret" }}'
        orchestration-secret: '{{ index . "orchestration-secret" }}'
        admin-password: '{{ index . "admin-password" }}'
        management-password: '{{ index . "management-password" }}'
        postgres-password: '{{ index . "postgres-password" }}'
        password: '{{ index . "password" }}'
        smtp-password: '{{ index . "smtp-password" }}'
        # For forward compatibility with keys will be used in 8.7.
        identity-admin-client-token: '{{ index . "password" }}'
        identity-connectors-client-token: '{{ index . "password" }}'
        identity-console-client-token: '{{ index . "password" }}'
        identity-orchestration-client-token: '{{ index . "password" }}'
        identity-operate-client-token: '{{ index . "password" }}'
        identity-optimize-client-token: '{{ index . "password" }}'
        identity-optimize-default-client-token: '{{ index . "optimize-secret" }}'
        identity-optimize-tenanta-client-token: '{{ index . "connectors-secret" }}'
        identity-optimize-tenantb-client-token: '{{ index . "console-secret" }}'
        identity-tasklist-client-token: '{{ index . "password" }}'
        identity-zeebe-client-token: '{{ index . "password" }}'
        # Should be removed after 8.7 alpha3.
        identity-admin-client-password: '{{ index . "password" }}'
        identity-connectors-client-password: '{{ index . "password" }}'
        identity-console-client-password: '{{ index . "password" }}'
        identity-orchestration-client-password: '{{ index . "password" }}'
        identity-operate-client-password: '{{ index . "password" }}'
        identity-optimize-client-password: '{{ index . "password" }}'
        identity-tasklist-client-password: '{{ index . "password" }}'
        identity-zeebe-client-password: '{{ index . "password" }}'
        ###
        identity-user-password: '{{ index . "password" }}'
        identity-keycloak-admin-password: '{{ index . "password" }}'
        identity-keycloak-postgresql-admin-password: '{{ index . "password" }}'
        identity-keycloak-postgresql-user-password: '{{ index . "password" }}'
        webmodeler-postgresql-admin-password: '{{ index . "password" }}'
        webmodeler-postgresql-user-password: '{{ index . "password" }}'
        # New keys for 8.8 defaults
        identity-postgresql-admin-password: '{{ index . "password" }}'
        identity-postgresql-user-password: '{{ index . "password" }}'
        web-modeler-postgresql-admin-password: '{{ index . "password" }}'
        web-modeler-postgresql-user-password: '{{ index . "password" }}'
        identity-migration-client-secret: '{{ index . "migration-secret" }}'
  dataFrom:
    - extract:
        key: integration-test
