---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: camunda-helm-existing-secrets-infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: infra-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: keycloak-admin-password
    remoteRef:
      key: products/distribution/ci
      property: CI_KEYCLOAK_ADMIN_PASSWORD
  - secretKey: elasticsearch-password
    remoteRef:
      key: products/distribution/ci
      property: CI_ELASTICSEARCH_PASSWORD
  - secretKey: kibana-password
    remoteRef:
      key: products/distribution/ci
      property: CI_KIBANA_PASSWORD
