---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: camunda-helm-existing-secrets-qa-keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: distribution-team
  target:
    name: qa-keycloak-admin-credentials  # name of the k8s Secret to be created
  data:
  - secretKey: identity-keycloak-admin-password
    remoteRef:
      key: qa-keycloak-admin
      property: password
