{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.postgresql.fullname" . }}
  labels:
    {{- include "keycloak.postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "keycloak.postgresql.secretKey" . }}: {{ .Values.postgresql.auth.password | default "keycloak" | b64enc | quote }}
{{- end }}
