{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "keycloak.secretKey" . }}: {{ .Values.auth.adminPassword | default "admin" | b64enc | quote }}
{{- end }}
