#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:fd2f22c0db21ee08ba74a10dba1ab9e0513b2e2bd974228afa140ba9eaad6e55"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:a75ddcccfc5bb7414718403c99a6a593b0d0b92305f285681f8346562c353e88"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-latest
    digest: "sha256:442279d0e13977ab1ba25ce01ebe145ceeca0019a8701e6217209e50c1075fbe"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:20183cda10c02c639174e8ddb729003eadec2a81df6b3c6491f4256a3448c24e"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:b95e9549e3c28f172cf28aaff94a088372cdec8fc68f9dd2e947e63ae16a496e"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:8ce38ae2d175a6774f43b90fb41d2d8b11c20aeaa36baa461c9bda088d6b6302"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:f0a148845827d11bbc854997351c17be1b5241c68154f556167576e3a48e78cb"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:349e5b0c513e10da8764dcc7cf25abd7ceb1719c5c4245d51c7d04cbd577f108"
