#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:e4655ec913ba4388e510dd6d5e772e945cfebe8adf7da26f7efe84dbb5d76f60"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:4faec90ee0bdd97ea0f3883d9e3d64d893e8c72582cbcba6f614ffa3df6ec568"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-latest
    digest: "sha256:ee002dd212ddababaa2a6d09039e64b10e4ffc318f7a7721981f2b829bb14dd8"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:ec560c446377de6bf7547778ccf258fa1a6ca6682dcd266f7f1d59cb5f430d5f"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: SNAPSHOT
      digest: "sha256:b21d57cabc52af6bbf7fef83969d93befb790df95699520c134c161339eafdea"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:b7bb3ff11950fa3b81b033c2cb7fe3948724896693633067f3433f3fda4d41bf"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:ba3a86afc4aec6ed5f16b041b9fd36eb3d5fa83f8f6ce2ed853eef849248cd6e"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:bce05c2dcdba0351940445be9faa619db033df7815ece7ed234b62520c77c210"
