#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.10-SNAPSHOT
    digest: "sha256:bc30049fadef54f289961198e93b47d495f99a6e225aafb900703cebcd436953"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.10-SNAPSHOT
    digest: "sha256:9736778f7389de6021e140af43a78255d94dd865f787c7614b50e13a64c65ca0"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.10-SNAPSHOT
    digest: "sha256:9303143b1d881c7272185db7f63fc96c4ebd2de77653e27544b8d8f2b95a457a"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/hub/tags
  restapi:
    image:
      repository: camunda/hub
      tag: SNAPSHOT

  # https://hub.docker.com/r/camunda/hub-websockets/tags
  websockets:
    image:
      repository: camunda/hub-websockets
      tag: SNAPSHOT

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.10-SNAPSHOT
    digest: "sha256:90162393f3b01de43eb25e05a620bf72be7e872b60f1ae58d91d8c5c9dd5f821"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:b45fdfb7364b577d9e5a24b1bb47a0706eafec4b763ea81bf925ba30efd82e19"
