#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:65c6998bb0cdcad5090a751e62165879a5079fefe29be3ae739d07dfd99378cd"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: SNAPSHOT
    digest: "sha256:4b0d0bd79b76ca7e48d3151e1ec77bbb50e9d1316251925e385c2db29d3f135f"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8-SNAPSHOT
    digest: "sha256:4c9c9e7d56f172f79d113ed02de0786d42ea4ef18af84e2fb9e6701110ee876a"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:ddc0b15e1adebfd9306f875da9602461092008f60bba3b3bb0d667325b5c55dd"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:e6a5291b9136f151e7f2fc2ad41d404a13c1ca0e842576c75337183b1b249a58"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: SNAPSHOT
    digest: "sha256:54639aaa29d88afe6117c6164ff8b520f3eb199853c7723f2f8fe2bd36b02f4b"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:6eacd5cede80f4c84c49b57123364d5d379a907b58167651e07e7e8dad077023"
