#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.10-SNAPSHOT
    digest: "sha256:bc30049fadef54f289961198e93b47d495f99a6e225aafb900703cebcd436953"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.10-SNAPSHOT
    digest: "sha256:296fa0fb0cb08d499c1f027e367e7b2498072e95686000d59ac1c02e6dc24909"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.10-SNAPSHOT
    digest: "sha256:7e45b263390adc8f261dc76c261f2e3faa49a2a4379ece6fadb7b8761a70d86d"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/hub/tags
  restapi:
    image:
      repository: camunda/hub
      tag: SNAPSHOT

  # https://hub.docker.com/r/camunda/hub-websockets/tags
  websockets:
    image:
      repository: camunda/hub-websockets
      tag: SNAPSHOT

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.10-SNAPSHOT
    digest: "sha256:9d758dfa3f8112fa17ee225717690cac7c0bf708988fff0938d43e34cc216c39"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:7a477f0580b70357bb4584eb2951ffd1c6fe9c94b1be23827d402519e809598f"
