# For more details about versions and the maintainer update procedure, see:
# docs/reference/release-process.md ("Minor Version Chores")
name: Get chart versions
description: Find chart versions that should be included in the CI matrix.
outputs:
  active:
    description: Versions selected for routine chart automation.
    value: ${{ steps.get-chart-versions.outputs.active }}

runs:
  using: composite
  steps:
    # NOTE: The checkout step is assumed to be done before this action is run.
    - name: Get chart versions
      shell: bash
      id: get-chart-versions
      run: |
        chart_versions_file="charts/chart-versions.yaml"
        yq -e '.chartAutomation.routineVersions | tag == "!!seq"' "$chart_versions_file" > /dev/null
        echo "active=$(yq '.chartAutomation.routineVersions | join(" ")' "$chart_versions_file")" >> "$GITHUB_OUTPUT"
