{{- if and .Values.global.ingress.enabled (not .Values.global.ingress.external) .Values.orchestration.enabled .Values.orchestration.contextPath (eq (include "camundaPlatform.orchestrationRESTTLSEnabled" .) "true") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-orchestration-http
  labels:
    {{- include "common.tplvalues.merge-overwrite" (dict
      "values" (list
        (include "camundaPlatform.labels" .)
        .Values.global.ingress.labels
      )
      "context" .
    ) | nindent 4 }}
  annotations:
    {{- $restProxyVerify := include "camundaPlatform.orchestrationProxyVerifyAnnotations" (dict "context" . "proto" "rest") | fromYaml }}
    {{- include "common.tplvalues.merge-overwrite" (dict
      "values" (list
        .Values.global.ingress.annotations
        (dict "nginx.ingress.kubernetes.io/backend-protocol" "HTTPS")
        ($restProxyVerify | default (dict))
      )
      "context" .
    ) | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    {{- if .Values.global.host }}
    - host: {{ tpl .Values.global.host $ }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - backend:
              service:
                name: {{ include "orchestration.serviceName" . }}
                port:
                  number: {{ .Values.orchestration.service.httpPort }}
            path: {{ .Values.orchestration.contextPath }}
            pathType: {{ .Values.global.ingress.pathType }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    {{- if eq .Values.global.ingress.tls.secretName "-" }}
    {{/* Use secretName: "-" to generate an empty TLS block for automatic certificate management. */}}
    {{/* This is useful for environments like OpenShift where the Ingress Operator manages certificates automatically. */}}
    - {}
    {{- else }}
    - hosts:
        - {{ tpl .Values.global.host $ }}
      {{- if .Values.global.ingress.tls.secretName }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
