#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:1b29e4687f3611c951699f35301b3d4f892a7fb097cfb48eaad21cf7a7911f69"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8.15
    digest: "sha256:2f9a3b033f18192bc2ae34c2a8d0de919e9f92538ac7adfe2c649d3bb2df1393"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8.31
    digest: "sha256:67456ef3651ed1a2761dc59da480c8f7a76c354506090b5517b2fca2ca9bb064"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: 8.8
      digest: "sha256:44d6673615ba0a04f57abfcbcc8aa7a06995ffae4c0dd1b6b0b11b5942504607"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: 8.8
      digest: "sha256:6097135ccc2d294dbfe3e6c3856e9dff8a14ebd1ce12b1bbf3021769bcf912b2"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: 8.8
      digest: "sha256:2b9efcf05b46d9aa25fbeefa5916c9e28ca9b883ef3b8ed2aa72527fefa4638b"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8.31
    digest: "sha256:088111cd5b44d242ec9a04c24574cce8c56d9ced24669f2ccdccf97853a71f3d"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8.15
    digest: "sha256:71f02fac0cbf3ea810c31ae6e74930da661e1f8b96b9601eff3e66d688450da5"
