#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: latest
    digest: "sha256:d7bdc3dcf211a0377be080a2a0a0a101aee167ea5fd6890d73779329b4bbcff4"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.8.10
    digest: "sha256:abed3406562ac2c363f78e56c0cc71b9f7764597d2ecfd13004149c181de859f"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.8.8
    digest: "sha256:ae781e69553127d3244f9f6f76183d4588b1cfbbb6622de36ee469c2188b8468"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: 8.8
      digest: "sha256:19d3518b7fbf62c84e4731e9038cf536018344ed2f06ad015d5da10c6ccdce1b"

  # https://hub.docker.com/r/camunda/web-modeler-webapp/tags
  webapp:
    image:
      repository: camunda/web-modeler-webapp
      tag: 8.8
      digest: "sha256:5615f4b84aa7949d04ff4cdfd7b2e56b5ae1f3b5c3559648df22ff9e4ef12ee8"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: 8.8
      digest: "sha256:250c781ff882df7df50eed258bf3c29ccfafd36f451dc7ea2ca50774b5c09fa2"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.8.21
    digest: "sha256:e2851adb2b6c85520a3b89f661ff3dc8847f34d3eeded2f657a3aa582ce0f217"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.8.10
    digest: "sha256:d44905a1e53beb1b5908152dbb4d01dde21ec1227ca1f209fb21808d3c924fd7"
