name: Workflow vars
description: Set common vars for workflow
inputs:
  setup-flow:
    description: The chart setup flow either "install", "upgrade-patch", or "upgrade-minor".
    default: "install"
  platform:
    description: The deployment cloud platform like GKE or ROSA.
  deployment-ttl:
    description: Define a ttl for the lifespan of the deployment
    required: false
    default: ""
  identifier-base:
    description: The fixed string in the identifier of the deployment it could be PR number or another specified name.
  chart-dir:
    description: A reference for the Camunda Helm chart directory which allows to test unreleased chagnes from Git repo.
    required: true
  chart-upgrade-version:
    description: The Helm chart version used in the upgrade-patch flow.
    required: false
    default: ""
  prefix:
    description: The prefix for the namespace. This is necessary because we only have permissions to create namespaces with a specific prefix.
    required: false
    default: ""

# NOTE: This is not an exclusive list, some vars are exported as env var not an output.
outputs:
  identifier:
    description: The unique identifier of the deployment where the workflow could be triggered by pull_request or workflow_dispatch.
    value: ${{ steps.vars.outputs.identifier }}
  ingress-host:
    description: Ingress hostname that will be used in the test
    value: ${{ steps.vars.outputs.ingress-host }}
  namespace:
    description: The namespace for the deployment
    value: ${{ steps.vars.outputs.namespace }}

runs:
  using: composite
  steps:
    - name: Configure Git safe directory
      shell: bash
      run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

    - name: Setup deploy-camunda
      uses: ./.github/actions/setup-deploy-camunda
    - name: Set workflow vars
      id: vars
      shell: bash
      run: |
        deploy-camunda ci workflow-vars \
          --platform "${{ inputs.platform }}" \
          --setup-flow "${{ inputs.setup-flow }}" \
          --deployment-ttl "${{ inputs.deployment-ttl }}" \
          --identifier-base "${{ inputs.identifier-base }}" \
          --chart-dir "${{ inputs.chart-dir }}" \
          --chart-upgrade-version "${{ inputs.chart-upgrade-version }}" \
          --prefix "${{ inputs.prefix }}" \
          --pr-number "${{ github.event.pull_request.number }}" \
          --run-id "${{ github.run_id }}"
