{{- if and (eq (include "camundaPlatform.orchestrationEnabled" .) "true") .Values.orchestration.serviceAccount.enabled -}}
{{- include "orchestration.renderZoneAware" (dict "manifest" "orchestration.serviceAccountManifest" "context" .) -}}
{{- end -}}
