{{- if and (eq (include "camundaPlatform.optimizeEnabled" .) "true") (not .Values.global.noSecondaryStorage) -}}
kind: ConfigMap
metadata:
  name: {{ include "optimize.fullname" . }}-configuration
  labels:
    {{- include "optimize.labels" . | nindent 4 }}
apiVersion: v1
data:
  environment-config.yaml: |
  {{- if .Values.optimize.configuration }}
    {{ .Values.optimize.configuration | indent 4 | trim }}
  {{- else }}
    {{- include "optimize.defaultConfig" . | trim | nindent 4 }}
  {{- end }}
  {{- if or .Values.global.identity.auth.enabled .Values.optimize.extraConfiguration }}
  application-ccsm.yaml: |
    {{- $springImport := include "optimize.springConfigImport" . }}
    {{- if $springImport }}
    spring:
      config:
        import: {{ $springImport }}
    {{- end }}
    {{- if .Values.global.identity.auth.enabled }}
    camunda:
      identity:
        clientId: {{ include "optimize.authClientId" . | quote }}
        audience: {{ include "optimize.authAudience" . | quote }}
        issuer: {{ include "camundaPlatform.authIssuerUrlWithFallback" . | quote }}
        issuerBackendUrl: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
      {{- $cslEnabled := eq (include "optimize.cslEnabled" .) "true" }}
      {{- if $cslEnabled }}
      security:
        authentication:
          method: "oidc"
          oidc:
            client-id: {{ include "optimize.authClientId" . | quote }}
            client-secret: ${VALUES_OPTIMIZE_CLIENT_SECRET:}
            audiences:
              - {{ include "optimize.authClientId" . | quote }}
              - {{ include "optimize.authAudience" . | quote }}
              - {{ (or .Values.global.identity.auth.camundaHub.clientApiAudience .Values.global.identity.auth.webModeler.clientApiAudience) | quote }}
            {{- if (include "camundaPlatform.authIssuerUrl" .) }}
            issuer-uri: {{ include "camundaPlatform.authIssuerUrl" . | quote }}
            {{- else }}
            authorization-uri: {{ include "camundaPlatform.authIssuerUrlEndpointAuth" . | quote }}
            jwk-set-uri: {{ include "camundaPlatform.authIssuerBackendUrlEndpointCerts" . | quote }}
            token-uri: {{ include "camundaPlatform.authIssuerBackendUrlEndpointToken" . | quote }}
            {{- end }}
            redirect-uri: "{baseUrl}/api/authentication/callback"
      {{- end }}
    {{- end }}
  {{- end }}

  {{- range .Values.optimize.extraConfiguration }}
  {{ .file }}: |
    {{ .content | indent 4 | trim }}
  {{- end }}
{{- end }}
