{{/*
This file name should start with an underscore to avoid rendering it as a template.
It is included (imported) in the ConfigMap.
*/}}
spring:
  profiles:
    active: {{ include "orchestration.enabledProfiles" . | quote }}

server:
  address: 0.0.0.0
  port: {{ .Values.orchestration.service.httpPort }}

management:
  server:
    address: 0.0.0.0
    port: {{ .Values.orchestration.service.managementPort }}
  {{- if .Values.orchestration.contextPath }}
  endpoint: {{ include "camundaPlatform.joinpath" (list .Values.orchestration.contextPath "actuator") | quote }}
  {{- end }}

camunda:
  system:
    cpu-thread-count: {{ .Values.orchestration.cpuThreadCount }}
    io-thread-count: {{ .Values.orchestration.ioThreadCount }}
    clock-controlled: false
    validate-restore-config: true
    upgrade:
      enable-version-check: true

  api:
    grpc:
      address: 0.0.0.0
      port: {{ .Values.orchestration.service.grpcPort }}

  cluster:
    network:
      host: 0.0.0.0
      {{- if gt (int .Values.global.multiregion.regions) 1 }}
      advertised-host: "${K8S_NAME}.${K8S_SERVICE_NAME}.${K8S_NAMESPACE}.svc"
      {{- else }}
      advertised-host: "${K8S_NAME}.${K8S_SERVICE_NAME}"
      {{- end }}
      command-api:
        host: 0.0.0.0
        port: {{ .Values.orchestration.service.commandPort }}
      internal-api:
        host: 0.0.0.0
        port: {{ .Values.orchestration.service.internalPort }}
    initial-contact-points:
      {{- range (untilStep 0 (int .Values.orchestration.clusterSize) 1) }}
        - {{ include "orchestration.fullname" $ }}-{{ . }}.${K8S_SERVICE_NAME}:{{$.Values.orchestration.service.internalPort}}
      {{- end }}
    # The Node ID depends on the StatefulSet Pod's name so it cannot be templated in the StatefulSet level.
    # The value of "node-id" is calculated in the "startup.sh" file and exported as "VALUES_NODE_ID" env var.
    node-id: ${VALUES_NODE_ID}
    partition-count: {{ .Values.orchestration.partitionCount | quote }}
    replication-factor: {{ .Values.orchestration.replicationFactor | quote }}
    size: {{ .Values.orchestration.clusterSize | quote }}
    name: {{ tpl .Values.global.zeebeClusterName . }}

  data:
    # TBA 8.9
    # retention:
    #   enabled: {{ .Values.orchestration.history.retention.enabled }}
    #   minimum-age: {{ .Values.orchestration.history.retention.minimumAge | quote }}
    snapshot-period: {{ .Values.orchestration.data.snapshotPeriod | quote }}
    primary-storage:
      disk:
        free-space:
          processing: {{ .Values.orchestration.data.disk.freeSpace.processing | quote }}
          replication: {{ .Values.orchestration.data.disk.freeSpace.replication | quote }}
    secondary-storage:
      type: {{ include "orchestration.secondaryStorage" . | quote -}}
      {{- if .Values.global.elasticsearch.enabled }}
      elasticsearch:
        url: {{ include "camundaPlatform.elasticsearchURL" . | quote }}
        cluster-name: {{ .Values.global.elasticsearch.clusterName | quote }}
        username: {{ .Values.global.elasticsearch.auth.username | quote }}
        password: ${VALUES_ELASTICSEARCH_PASSWORD:}
        index-prefix: {{ .Values.global.elasticsearch.prefix | quote }}
        history:
          policy-name: {{ .Values.orchestration.history.retention.policyName | quote }}
      {{- end }}
      {{- if .Values.global.opensearch.enabled }}
      opensearch:
        url: {{ include "camundaPlatform.opensearchURL" . | quote }}
        cluster-name: {{ .Values.global.opensearch.clusterName | quote }}
        username: {{ .Values.global.opensearch.auth.username | quote }}
        password: ${VALUES_OPENSEARCH_PASSWORD:}
        index-prefix: {{ .Values.global.opensearch.prefix | quote }}
        history:
          policy-name: {{ .Values.orchestration.history.retention.policyName | quote }}
    {{- end }}


  # TBA 8.9
  # security:
  #   base-url: {{ include "identity.internalUrl" . | quote }}
  #   issuer-url: {{ include "camundaPlatform.authIssuerUrl" . | quote }}
  #   issuer-backend-url: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
  #   redirect-root-url: {{ tpl .Values.global.identity.auth.orchestration.redirectUrl . | quote }}
  #   client-secret: ${VALUES_CAMUNDA_ORCHESTRATION_CLIENT_SECRET:}
  #   audience: {{ include "orchestration.authAudience" . | quote }}
  #   authentication:
  #     unprotected-api: {{ .Values.orchestration.security.authentication.unprotectedApi }}
  #     method: {{ .Values.orchestration.security.authentication.method | quote }}
  #     {{- if eq .Values.orchestration.security.authentication.method "oidc" }}
  #     oidc:
  #       client-id: {{ include "orchestration.authClientId" . | quote }}
  #     {{- end }}
  #   authorization: {{ .Values.orchestration.security.authorizations.enabled }}
  #   multi-tenancy:
  #     checks: {{ include "orchestration.multitenancyChecksEnabled" . }}
  #     api: {{ include "orchestration.multitenancyApiEnabled" . }}
