{{- if .Values.capacityManager.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "capacityManager.fullname" . }}
  labels: {{- include "capacityManager.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    resourceNames: [{{ include "orchestration.fullname" . | quote }}]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
{{- end -}}
