{{- if and .Values.capacityManager.enabled .Values.capacityManager.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capacityManager.serviceAccountName" . }}
  labels:
    {{- include "capacityManager.labels" . | nindent 4 }}
    {{- with .Values.capacityManager.serviceAccount.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.capacityManager.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: true
{{- end -}}
