// Copyright 2026 Camunda Services GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ci-failure-diagnoser reads a `diagnostics/` directory produced by
// `deploy-camunda matrix run`, asks Claude to diagnose the most likely root
// cause, and writes a markdown report. Designed to run in GitHub Actions
// `workflow_run` jobs after an integration-test failure.
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"time"
)

const (
	defaultPodLogTrim     = 4096 // ≈4 KB per pod, tail-biased
	defaultRequestTimeout = 90 * time.Second
)

func main() {
	var (
		diagDir      = flag.String("diagnostics-dir", "diagnostics", "Path to diagnostics artifact root")
		outputPath   = flag.String("output", "", "Write markdown report here (default: stdout)")
		chartVersion = flag.String("chart-version", "", "Chart version under test (e.g. 8.10)")
		scenario     = flag.String("scenario", "", "Scenario name (e.g. elasticsearch)")
		flow         = flag.String("flow", "", "Flow (install, upgrade-minor, upgrade-patch)")
		platform     = flag.String("platform", "", "Cloud platform (gke, eks, rosa)")
		shortname    = flag.String("shortname", "", "Scenario shortname (e.g. es)")
		identity     = flag.String("identity", "", "Identity selection")
		persistence  = flag.String("persistence", "", "Persistence selection")
		workflowURL  = flag.String("workflow-url", "", "GitHub Actions run URL")
		podLogTrim   = flag.Int("pod-log-trim", defaultPodLogTrim, "Max bytes of tail per pod log")
	)
	flag.Parse()

	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		fmt.Fprintln(os.Stderr, "ANTHROPIC_API_KEY is not set; skipping diagnosis (exit 0)")
		return
	}

	d, err := LoadDiagnostics(*diagDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "no diagnostics to analyse: %v\n", err)
		return // exit 0 — diagnostics may legitimately be absent (e.g. failure before kubectl context was set)
	}
	d.TrimLogs(*podLogTrim)

	ctx := Context{
		ChartVersion: *chartVersion,
		Scenario:     *scenario,
		Flow:         *flow,
		Platform:     *platform,
		Shortname:    *shortname,
		Identity:     *identity,
		Persistence:  *persistence,
		WorkflowURL:  *workflowURL,
	}
	user := BuildUserMessage(ctx, d)

	model := os.Getenv("ANTHROPIC_MODEL")
	client := NewAnthropicClient(apiKey, model)

	rctx, cancel := context.WithTimeout(context.Background(), defaultRequestTimeout)
	defer cancel()

	answer, err := client.Diagnose(rctx, systemPrompt, user)
	if err != nil {
		fmt.Fprintf(os.Stderr, "anthropic call failed: %v\n", err)
		os.Exit(1)
	}

	report := assembleReport(ctx, answer)
	if err := writeOutput(*outputPath, report); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}
}

func assembleReport(ctx Context, answer string) string {
	header := "## :robot_face: CI failure diagnosis\n\n"
	if ctx.ChartVersion != "" || ctx.Scenario != "" || ctx.Flow != "" || ctx.Platform != "" {
		header += fmt.Sprintf("**Scenario:** `%s` · **Flow:** `%s` · **Platform:** `%s` · **Chart:** `%s`\n\n",
			fallback(ctx.Scenario, "?"), fallback(ctx.Flow, "?"), fallback(ctx.Platform, "?"), fallback(ctx.ChartVersion, "?"))
	}
	footer := "\n\n---\n_Generated by `scripts/ci-failure-diagnoser`. This is a machine-generated diagnosis — verify before acting._"
	return header + answer + footer
}

func writeOutput(path, body string) error {
	if path == "" {
		fmt.Print(body)
		if !endsWithNewline(body) {
			fmt.Println()
		}
		return nil
	}
	return os.WriteFile(path, []byte(body), 0o644)
}

func endsWithNewline(s string) bool {
	return len(s) > 0 && s[len(s)-1] == '\n'
}
