{{- if and .Values.prometheusServiceMonitor.enabled (eq (include "camundaHub.consoleEnabled" .) "true") -}}
{{- $consoleVals := include "camundaHub.consoleValues" . | fromYaml -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-console
  labels: {{- include "camundaPlatform.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheusServiceMonitor.labels | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.global.labels | nindent 6 }}
      app.kubernetes.io/component: console
  endpoints:
    - honorLabels: true
      path: {{ include "camundaPlatform.joinpath" (list $consoleVals.contextPath $consoleVals.metrics.prometheus) }}
      port: metrics
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
{{- end }}
