{{- if and .Values.prometheusServiceMonitor.enabled (eq (include "camundaHub.webModelerEnabled" .) "true") -}}
{{- $wmVals := include "camundaHub.webModelerValues" . | fromYaml -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-modeler
  labels: {{- include "camundaPlatform.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheusServiceMonitor.labels | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.global.labels | nindent 6 }}
      app.kubernetes.io/component: restapi
  endpoints:
    - honorLabels: true
      path: {{ $wmVals.restapi.metrics.prometheus }}
      port: http-management
      interval: {{ .Values.prometheusServiceMonitor.scrapeInterval }}
{{- end }}
