{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webModeler.fullname" . }}-websockets-configuration
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
data:
  {{- if (dig "webModeler" "websockets" "configuration" .Values.webModeler.websockets.configuration .Values.camundaHub) }}
  application.yaml: |
    {{ (dig "webModeler" "websockets" "configuration" .Values.webModeler.websockets.configuration .Values.camundaHub) | indent 4 | trim }}
  {{- else }}
  application.yaml: |
  {{- end }}
  {{- include "camundaPlatform.renderExtraConfiguration" (dict "extraConfig" (dig "webModeler" "websockets" "extraConfiguration" .Values.webModeler.websockets.extraConfiguration .Values.camundaHub)) }}
{{- end }}
