{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webModeler.fullname" . }}-configuration
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
data:
  pusher-app-id: web-modeler
  {{- if (or .Values.camundaHub.webModeler.configuration .Values.webModeler.configuration) }}
  application.yaml: |
    {{ (or .Values.camundaHub.webModeler.configuration .Values.webModeler.configuration) | indent 4 | trim }}
  {{- end }}
  {{- include "camundaPlatform.renderExtraConfiguration" (dict "extraConfig" (or .Values.camundaHub.webModeler.extraConfiguration .Values.webModeler.extraConfiguration)) }}
{{- end }}
