{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
{{- $wmVals := include "camundaHub.webModelerValues" . | fromYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webModeler.fullname" . }}-websockets-configuration
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
data:
  {{- if $wmVals.websockets.configuration }}
  application.yaml: |
    {{ $wmVals.websockets.configuration | indent 4 | trim }}
  {{- else }}
  application.yaml: |
  {{- end }}
  {{- include "camundaPlatform.renderExtraConfiguration" (dict "extraConfig" $wmVals.websockets.extraConfiguration) }}
{{- end }}
