{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webModeler.fullname" . }}-restapi-configuration
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
data:
  {{- if (dig "webModeler" "restapi" "configuration" .Values.webModeler.restapi.configuration .Values.camundaHub) }}
  application.yaml: |
    {{ (dig "webModeler" "restapi" "configuration" .Values.webModeler.restapi.configuration .Values.camundaHub) | indent 4 | trim }}
  {{- else }}
  application.yaml: |
    camunda:
      {{- if or .Values.global.identity.auth.enabled (eq (include "webModeler.authMethod" .) "oidc") }}
      identity:
        {{- if .Values.identity.enabled }}
        base-url: {{ include "camundaPlatform.identityURL" . | quote }}
        issuer: {{ include "camundaPlatform.authIssuerUrlWithFallback" . | quote }}
        issuerBackendUrl: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
        {{- end }}
        type: {{ include "camundaPlatform.authIssuerType" . | quote }}
      {{- end }}

      modeler:
        feature:
          play-enabled: {{ ternary "false" "true" .Values.global.noSecondaryStorage | quote }}

        pusher:
          host: {{ include "webModeler.websockets.fullname" . | quote }}
          port: {{ (dig "webModeler" "websockets" "service" "port" .Values.webModeler.websockets.service.port .Values.camundaHub) }}
          client:
            host: {{ include "webModeler.publicWebsocketHost" . | quote }}
            port: {{ include "webModeler.publicWebsocketPort" . | quote }}
            {{- if and .Values.global.ingress.enabled (or .Values.camundaHub.webModeler.contextPath .Values.webModeler.contextPath) }}
            path: {{ include "webModeler.websocketContextPath" . | quote }}
            {{- end }}
            force-tls: {{ include "webModeler.websocketTlsEnabled" . }}

        {{- if or .Values.global.identity.auth.enabled (eq (include "webModeler.authMethod" .) "oidc") }}
        security:
          jwt:
            issuer:
              backend-url: {{ include "camundaPlatform.authIssuerBackendUrl" . | quote }}
            audience:
              internal-api: {{ include "webModeler.authClientApiAudience" . | quote }}
              public-api: {{ include "webModeler.authPublicApiAudience" . | quote }}
        {{- end }}

        mail:
          from-address: {{ required "The value 'webModeler.restapi.mail.fromAddress' is required" (dig "webModeler" "restapi" "mail" "fromAddress" .Values.webModeler.restapi.mail.fromAddress .Values.camundaHub) | quote }}
          from-name: {{ (dig "webModeler" "restapi" "mail" "fromName" .Values.webModeler.restapi.mail.fromName .Values.camundaHub) | quote }}

        oauth2:
          client-id: {{ include "webModeler.authClientId" . | quote }}
          token:
            username-claim: {{ .Values.orchestration.security.authentication.oidc.usernameClaim | quote }}

        server:
          url: {{ tpl (or .Values.global.identity.auth.camundaHub.webModeler.redirectUrl .Values.global.identity.auth.webModeler.redirectUrl) $ | quote }}
          https-only: {{ hasPrefix "https://" (tpl (or .Values.global.identity.auth.camundaHub.webModeler.redirectUrl .Values.global.identity.auth.webModeler.redirectUrl) $) | quote }}

        {{- if or .Values.orchestration.enabled (dig "webModeler" "restapi" "clusters" .Values.webModeler.restapi.clusters .Values.camundaHub) }}
        clusters:
          {{- if (dig "webModeler" "restapi" "clusters" .Values.webModeler.restapi.clusters .Values.camundaHub) }}
            {{- (dig "webModeler" "restapi" "clusters" .Values.webModeler.restapi.clusters .Values.camundaHub) | toYaml | nindent 10 }}
          {{- else}}
          - id: "default-cluster"
            name: {{ tpl .Values.global.zeebeClusterName . | quote }}
            version: {{ include "camundaPlatform.imageTagByParams" (dict "base" .Values.global "overlay" .Values.orchestration) | quote }}
            authentication: {{ include "webModeler.authConfigValue" . | quote }}
            authorizations:
              enabled: {{ .Values.orchestration.security.authorizations.enabled }}
            url:
              grpc: {{ include "camundaPlatform.orchestrationGRPCInternalURL" . | quote }}
              rest: {{ include "camundaPlatform.orchestrationHTTPInternalURL" . | quote }}
              web-app: {{ include "camundaPlatform.orchestrationExternalURL" . | quote }}
          {{- end }}
        {{- end }}

    spring:
      {{- if (dig "webModeler" "restapi" "extraConfiguration" .Values.webModeler.restapi.extraConfiguration .Values.camundaHub) }}
      config:
        import:
        {{- range (dig "webModeler" "restapi" "extraConfiguration" .Values.webModeler.restapi.extraConfiguration .Values.camundaHub) }}
          - optional:file:/home/runner/config/{{ .file }}
        {{- end }}
      {{- end }}
      datasource:
        url: {{ include "webModeler.restapi.databaseUrl" . | quote }}
        username: {{ include "webModeler.restapi.databaseUser" . | quote }}

      mail:
        host: {{ (dig "webModeler" "restapi" "mail" "smtpHost" .Values.webModeler.restapi.mail.smtpHost .Values.camundaHub) | quote }}
        port: {{ (dig "webModeler" "restapi" "mail" "smtpPort" .Values.webModeler.restapi.mail.smtpPort .Values.camundaHub) }}
        {{- if (dig "webModeler" "restapi" "mail" "smtpUser" .Values.webModeler.restapi.mail.smtpUser .Values.camundaHub) }}
        username: {{ (dig "webModeler" "restapi" "mail" "smtpUser" .Values.webModeler.restapi.mail.smtpUser .Values.camundaHub) | quote }}
        {{- end }}
        properties:
          mail.smtp.auth: {{ include "webModeler.restapi.mail.authEnabled" . }}
          mail.smtp.starttls.enable: {{ (dig "webModeler" "restapi" "mail" "smtpTlsEnabled" .Values.webModeler.restapi.mail.smtpTlsEnabled .Values.camundaHub) }}
          mail.smtp.starttls.required: {{ (dig "webModeler" "restapi" "mail" "smtpTlsEnabled" .Values.webModeler.restapi.mail.smtpTlsEnabled .Values.camundaHub) }}

      security:
        oauth2:
          resourceserver:
            {{- if or .Values.global.identity.auth.enabled (eq (include "webModeler.authMethod" .) "oidc") }}
            jwt:
              issuer-uri: {{ include "camundaPlatform.authIssuerUrlWithFallback" . | quote }}
              jwk-set-uri: {{ include "camundaPlatform.authIssuerBackendUrlEndpointCerts" . | quote }}
            {{- else }}
            jwt: null
            {{- end }}

      servlet:
        multipart:
          max-file-size: {{ .Values.global.config.requestBodySize | quote }}
          max-request-size: {{ .Values.global.config.requestBodySize | quote }}

    {{- if (or .Values.camundaHub.webModeler.contextPath .Values.webModeler.contextPath) }}
    server:
      servlet:
        context-path: {{ include "camundaPlatform.joinpath" (list (or .Values.camundaHub.webModeler.contextPath .Values.webModeler.contextPath)) | quote }}
    management:
      server:
        base-path: {{ include "camundaPlatform.joinpath" (list (or .Values.camundaHub.webModeler.contextPath .Values.webModeler.contextPath)) | quote }}
    {{- end }}

    logging:
{{- with (dig "webModeler" "restapi" "logging" .Values.webModeler.restapi.logging .Values.camundaHub) }}
{{ . | toYaml | indent 6 }}
{{- end }}
  {{- end }}
  {{- include "camundaPlatform.renderExtraConfiguration" (dict "extraConfig" (dig "webModeler" "restapi" "extraConfiguration" .Values.webModeler.restapi.extraConfiguration .Values.camundaHub)) }}
{{- end }}
