{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
{{- $wmVals := include "camundaHub.webModelerValues" . | fromYaml -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webModeler.websockets.fullname" . }}
  labels: {{- include "webModeler.websockets.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels: {{- include "webModeler.websockets.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "webModeler.websockets.labels" . | nindent 8 }}
      {{- if $wmVals.websockets.podLabels }}
      {{- tpl (toYaml $wmVals.websockets.podLabels) $ | nindent 8 }}
      {{- end }}
      {{- if $wmVals.websockets.podAnnotations }}
      annotations:
        {{- tpl (toYaml $wmVals.websockets.podAnnotations) $ | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        {{- include "webModeler.imagePullSecrets" . | nindent 8 }}
      initContainers:
        {{- tpl ($wmVals.websockets.initContainers | default list | toYaml | nindent 8) $ }}
      containers:
        - name: {{ include "webModeler.name" . }}-websockets
          image: {{ include "webModeler.websockets.image" . | quote }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if $wmVals.websockets.containerSecurityContext }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $wmVals.websockets.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "CAMUNDA_LICENSE_KEY"
                "config" .Values.global.license
            ) | nindent 12 }}
            - name: APP_NAME
              value: "Web Modeler WebSockets"
            - name: PUSHER_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "webModeler.fullname" . }}-configuration
                  key: pusher-app-id
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "PUSHER_APP_KEY"
                "config" $wmVals.restapi.pusher.client
                "defaultSecretName" (include "webModeler.fullname" .)
                "defaultSecretKey" "pusher-app-key"
            ) | nindent 12 }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "PUSHER_APP_SECRET"
                "config" $wmVals.restapi.pusher
                "defaultSecretName" (include "webModeler.fullname" .)
                "defaultSecretKey" "pusher-app-secret"
            ) | nindent 12 }}
            {{- if and .Values.global.ingress.enabled $wmVals.contextPath }}
            - name: PUSHER_APP_PATH
              value: {{ include "webModeler.websocketContextPath" . | quote }}
            {{- end }}
          {{- with $wmVals.websockets.env }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- if $wmVals.websockets.envFrom }}
          envFrom:
            {{- $wmVals.websockets.envFrom | toYaml | nindent 12 }}
          {{- end }}
          {{- if $wmVals.websockets.command}}
          command: {{ toYaml $wmVals.websockets.command | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml $wmVals.websockets.resources | nindent 12 }}
          ports:
            - containerPort: 8060
              name: http
              protocol: TCP
          {{- if $wmVals.websockets.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ $wmVals.websockets.startupProbe.probePath }}
              scheme: {{ $wmVals.websockets.startupProbe.scheme }}
              port: http
            initialDelaySeconds: {{ $wmVals.websockets.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ $wmVals.websockets.startupProbe.periodSeconds }}
            successThreshold: {{ $wmVals.websockets.startupProbe.successThreshold }}
            failureThreshold: {{ $wmVals.websockets.startupProbe.failureThreshold }}
            timeoutSeconds: {{ $wmVals.websockets.startupProbe.timeoutSeconds }}
          {{- end }}
          {{- if $wmVals.websockets.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $wmVals.websockets.readinessProbe.probePath }}
              scheme: {{ $wmVals.websockets.readinessProbe.scheme }}
              port: http
            initialDelaySeconds: {{ $wmVals.websockets.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $wmVals.websockets.readinessProbe.periodSeconds }}
            successThreshold: {{ $wmVals.websockets.readinessProbe.successThreshold }}
            failureThreshold: {{ $wmVals.websockets.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ $wmVals.websockets.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if $wmVals.websockets.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $wmVals.websockets.livenessProbe.probePath }}
              scheme: {{ $wmVals.websockets.livenessProbe.scheme }}
              port: http
            initialDelaySeconds: {{ $wmVals.websockets.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $wmVals.websockets.livenessProbe.periodSeconds }}
            successThreshold: {{ $wmVals.websockets.livenessProbe.successThreshold }}
            failureThreshold: {{ $wmVals.websockets.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ $wmVals.websockets.livenessProbe.timeoutSeconds }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /home/webapp/config/application.yaml
              subPath: application.yaml
          {{- with $wmVals.websockets.extraConfiguration }}
          {{- include "camundaPlatform.extraConfigurationVolumeMounts" (dict "extraConfig" . "volumeName" "config" "basePath" "/home/webapp/config") | trim | nindent 12 }}
          {{- end }}
          {{- if $wmVals.websockets.extraVolumeMounts }}
          {{- $wmVals.websockets.extraVolumeMounts | toYaml | nindent 12 }}
          {{- end }}
        {{- if $wmVals.websockets.sidecars }}
        {{- $wmVals.websockets.sidecars | toYaml | nindent 8 }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "webModeler.fullname" . }}-websockets-configuration
      {{- if $wmVals.websockets.extraVolumes }}
      {{- $wmVals.websockets.extraVolumes | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webModeler.serviceAccountName" . }}
      {{- if $wmVals.websockets.dnsConfig }}
      dnsConfig: {{- toYaml $wmVals.websockets.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if $wmVals.websockets.dnsPolicy }}
      dnsPolicy: {{ $wmVals.websockets.dnsPolicy | quote }}
      {{- end }}
      {{- if $wmVals.websockets.podSecurityContext }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $wmVals.websockets.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- with $wmVals.websockets.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $wmVals.websockets.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $wmVals.websockets.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
