{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
{{- $deploymentStrategy := (or .Values.camundaHub.persistence.deploymentStrategy .Values.webModeler.persistence.deploymentStrategy) | default "RollingUpdate" -}}
{{- if not (has $deploymentStrategy (list "RollingUpdate" "Recreate")) -}}
{{- fail "webModeler.persistence.deploymentStrategy value must be one of 'RollingUpdate', 'Recreate'" -}}
{{- end -}}
{{- if and (eq $deploymentStrategy "Recreate") (not (or .Values.camundaHub.persistence.enabled .Values.webModeler.persistence.enabled)) -}}
{{- fail "webModeler.persistence.deploymentStrategy: Recreate requires webModeler.persistence.enabled: true. The default chart-managed path uses a per-pod ephemeral volume with no Multi-Attach contention, so Recreate is only useful when existingClaim points to a ReadWriteOnce volume; without persistence it only adds upgrade downtime" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webModeler.restapi.fullname" . }}
  labels: {{- include "webModeler.restapi.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  strategy:
    type: {{ $deploymentStrategy }}
  replicas: {{ (or .Values.camundaHub.restapi.replicas .Values.webModeler.restapi.replicas) }}
  selector:
    matchLabels: {{- include "webModeler.restapi.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "webModeler.restapi.labels" . | nindent 8 }}
      {{- if (or .Values.camundaHub.restapi.podLabels .Values.webModeler.restapi.podLabels) }}
      {{- tpl (toYaml (or .Values.camundaHub.restapi.podLabels .Values.webModeler.restapi.podLabels)) $ | nindent 8 }}
      {{- end }}
      {{- if or (and (eq (include "camundaPlatform.hasCaBundle" .) "true") .Values.global.tls.caBundle.autoRollout) (or .Values.camundaHub.restapi.podAnnotations .Values.webModeler.restapi.podAnnotations) }}
      annotations:
        {{- with (include "camundaPlatform.caBundleChecksumAnnotation" .) }}{{ . | nindent 8 }}{{- end }}
        {{- with (or .Values.camundaHub.restapi.podAnnotations .Values.webModeler.restapi.podAnnotations) }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      imagePullSecrets:
        {{- include "webModeler.imagePullSecrets" . | nindent 8 }}
      initContainers:
        {{- if eq (include "camundaPlatform.hasCaBundle" .) "true" }}
        {{- include "camundaPlatform.caBundleInitContainer" (dict "context" $ "image" (include "webModeler.restapi.image" $)) | nindent 8 }}
        {{- end }}
        {{- with (or .Values.camundaHub.restapi.initContainers .Values.webModeler.restapi.initContainers) }}
        {{- tpl (toYaml . | nindent 8) $ }}
        {{- end }}
      containers:
        - name: {{ include "webModeler.name" . }}-restapi
          image: {{ include "webModeler.restapi.image" . | quote }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if (or .Values.camundaHub.restapi.containerSecurityContext .Values.webModeler.restapi.containerSecurityContext) }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" (or .Values.camundaHub.restapi.containerSecurityContext .Values.webModeler.restapi.containerSecurityContext) "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "CAMUNDA_LICENSE_KEY"
                "config" .Values.global.license
            ) | nindent 12 }}
            - name: JAVA_OPTIONS
              value: {{ (or .Values.camundaHub.restapi.javaOpts .Values.webModeler.restapi.javaOpts) | default "-XX:MaxRAMPercentage=80.0" | quote }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "SPRING_DATASOURCE_PASSWORD"
                "config" (or .Values.camundaHub.restapi.externalDatabase .Values.webModeler.restapi.externalDatabase)
            ) | nindent 12 }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "RESTAPI_MAIL_PASSWORD"
                "config" (or .Values.camundaHub.restapi.mail .Values.webModeler.restapi.mail)
            ) | nindent 12 }}
            - name: RESTAPI_PUSHER_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "webModeler.fullname" . }}-configuration
                  key: pusher-app-id
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "RESTAPI_PUSHER_KEY"
                "config" (mustMergeOverwrite (deepCopy .Values.webModeler.restapi.pusher.client) .Values.camundaHub.restapi.pusher.client)
                "defaultSecretName" (include "webModeler.fullname" .)
                "defaultSecretKey" "pusher-app-key"
            ) | nindent 12 }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "RESTAPI_PUSHER_SECRET"
                "config" (mustMergeOverwrite (deepCopy .Values.webModeler.restapi.pusher) .Values.camundaHub.restapi.pusher)
                "defaultSecretName" (include "webModeler.fullname" .)
                "defaultSecretKey" "pusher-app-secret"
            ) | nindent 12 }}
            - name: ZEEBE_CLIENT_CONFIG_PATH
              value: {{ (or .Values.camundaHub.restapi.zeebeClientConfigPath .Values.webModeler.restapi.zeebeClientConfigPath) | default "/tmp/zeebe_client_cache.txt" | quote }}
            - name: CAMUNDA_MODELER_FEATURE_CONSOLE_ENABLED
              value: {{ include "camundaHub.consoleEnabled" . | quote }}
            - name: CAMUNDA_MODELER_FEATURE_GLOBAL_NAVIGATION_V2_ENABLED
              value: "false"
            {{- if and .Values.global.documentStore.type.aws.enabled (not .Values.global.documentStore.type.aws.irsa.enabled) }}
            - name: AWS_ACCESS_KEY_ID
              {{- include "camundaPlatform.emitAwsDocumentStoreSecret" (dict
                  "secretType" "accessKeyId"
                  "context" .
              ) | nindent 14 }}
            - name: AWS_SECRET_ACCESS_KEY
              {{- include "camundaPlatform.emitAwsDocumentStoreSecret" (dict
                  "secretType" "secretAccessKey"
                  "context" .
              ) | nindent 14 }}
            {{- end }}
            {{- if eq (lower .Values.global.documentStore.activeStoreId) "gcp" }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ printf "%s/%s" .Values.global.documentStore.type.gcp.mountPath .Values.global.documentStore.type.gcp.fileName | quote }}
            {{- end }}
          {{- if eq (include "camundaPlatform.hasCaBundle" .) "true" }}
            {{- include "camundaPlatform.caBundleEnv" . | nindent 12 }}
            {{- include "camundaPlatform.caBundleJavaToolOptionsEnv" . | nindent 12 }}
          {{- end }}
          {{- with (or .Values.camundaHub.restapi.env .Values.webModeler.restapi.env) }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- $documentStoreEnvFrom := ne (include "camundaPlatform.extraConfigHasPath" (dict "extraConfiguration" (or .Values.camundaHub.restapi.extraConfiguration .Values.webModeler.restapi.extraConfiguration) "path" (list "camunda" "document"))) "true" }}
          {{- if or $documentStoreEnvFrom (or .Values.camundaHub.restapi.envFrom .Values.webModeler.restapi.envFrom) }}
          envFrom:
          {{- if $documentStoreEnvFrom }}
            - configMapRef:
                name: {{ include "camundaPlatform.fullname" . }}-documentstore-env-vars
          {{- end }}
          {{- if (or .Values.camundaHub.restapi.envFrom .Values.webModeler.restapi.envFrom) }}
            {{- (or .Values.camundaHub.restapi.envFrom .Values.webModeler.restapi.envFrom) | toYaml | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if (or .Values.camundaHub.restapi.command .Values.webModeler.restapi.command) }}
          command: {{ toYaml (or .Values.camundaHub.restapi.command .Values.webModeler.restapi.command) | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml (or .Values.camundaHub.restapi.resources .Values.webModeler.restapi.resources) | nindent 12 }}
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
            - containerPort: 8091
              name: http-management
              protocol: TCP
          {{- if (or .Values.camundaHub.restapi.startupProbe.enabled .Values.webModeler.restapi.startupProbe.enabled) }}
          startupProbe:
            httpGet:
              path: {{ include "camundaPlatform.joinpath" (list (or .Values.camundaHub.contextPath .Values.webModeler.contextPath) (or .Values.camundaHub.restapi.startupProbe.probePath .Values.webModeler.restapi.startupProbe.probePath)) }}
              scheme: {{ (or .Values.camundaHub.restapi.startupProbe.scheme .Values.webModeler.restapi.startupProbe.scheme) }}
              port: http-management
            initialDelaySeconds: {{ (or .Values.camundaHub.restapi.startupProbe.initialDelaySeconds .Values.webModeler.restapi.startupProbe.initialDelaySeconds) }}
            periodSeconds: {{ (or .Values.camundaHub.restapi.startupProbe.periodSeconds .Values.webModeler.restapi.startupProbe.periodSeconds) }}
            successThreshold: {{ (or .Values.camundaHub.restapi.startupProbe.successThreshold .Values.webModeler.restapi.startupProbe.successThreshold) }}
            failureThreshold: {{ (or .Values.camundaHub.restapi.startupProbe.failureThreshold .Values.webModeler.restapi.startupProbe.failureThreshold) }}
            timeoutSeconds: {{ (or .Values.camundaHub.restapi.startupProbe.timeoutSeconds .Values.webModeler.restapi.startupProbe.timeoutSeconds) }}
          {{- end }}
          {{- if (or .Values.camundaHub.restapi.readinessProbe.enabled .Values.webModeler.restapi.readinessProbe.enabled) }}
          readinessProbe:
            httpGet:
              path: {{ include "camundaPlatform.joinpath" (list (or .Values.camundaHub.contextPath .Values.webModeler.contextPath) (or .Values.camundaHub.restapi.readinessProbe.probePath .Values.webModeler.restapi.readinessProbe.probePath)) }}
              scheme: {{ (or .Values.camundaHub.restapi.readinessProbe.scheme .Values.webModeler.restapi.readinessProbe.scheme) }}
              port: http-management
            initialDelaySeconds: {{ (or .Values.camundaHub.restapi.readinessProbe.initialDelaySeconds .Values.webModeler.restapi.readinessProbe.initialDelaySeconds) }}
            periodSeconds: {{ (or .Values.camundaHub.restapi.readinessProbe.periodSeconds .Values.webModeler.restapi.readinessProbe.periodSeconds) }}
            successThreshold: {{ (or .Values.camundaHub.restapi.readinessProbe.successThreshold .Values.webModeler.restapi.readinessProbe.successThreshold) }}
            failureThreshold: {{ (or .Values.camundaHub.restapi.readinessProbe.failureThreshold .Values.webModeler.restapi.readinessProbe.failureThreshold) }}
            timeoutSeconds: {{ (or .Values.camundaHub.restapi.readinessProbe.timeoutSeconds .Values.webModeler.restapi.readinessProbe.timeoutSeconds) }}
          {{- end }}
          {{- if (or .Values.camundaHub.restapi.livenessProbe.enabled .Values.webModeler.restapi.livenessProbe.enabled) }}
          livenessProbe:
            httpGet:
              path: {{ include "camundaPlatform.joinpath" (list (or .Values.camundaHub.contextPath .Values.webModeler.contextPath) (or .Values.camundaHub.restapi.livenessProbe.probePath .Values.webModeler.restapi.livenessProbe.probePath)) }}
              scheme: {{ (or .Values.camundaHub.restapi.livenessProbe.scheme .Values.webModeler.restapi.livenessProbe.scheme) }}
              port: http-management
            initialDelaySeconds: {{ (or .Values.camundaHub.restapi.livenessProbe.initialDelaySeconds .Values.webModeler.restapi.livenessProbe.initialDelaySeconds) }}
            periodSeconds: {{ (or .Values.camundaHub.restapi.livenessProbe.periodSeconds .Values.webModeler.restapi.livenessProbe.periodSeconds) }}
            successThreshold: {{ (or .Values.camundaHub.restapi.livenessProbe.successThreshold .Values.webModeler.restapi.livenessProbe.successThreshold) }}
            failureThreshold: {{ (or .Values.camundaHub.restapi.livenessProbe.failureThreshold .Values.webModeler.restapi.livenessProbe.failureThreshold) }}
            timeoutSeconds: {{ (or .Values.camundaHub.restapi.livenessProbe.timeoutSeconds .Values.webModeler.restapi.livenessProbe.timeoutSeconds) }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /home/runner/config/application.yaml
              subPath: application.yaml
          {{- with (or .Values.camundaHub.restapi.extraConfiguration .Values.webModeler.restapi.extraConfiguration) }}
          {{- include "camundaPlatform.extraConfigurationVolumeMounts" (dict "extraConfig" . "volumeName" "config" "basePath" "/home/runner/config") | trim | nindent 12 }}
          {{- end }}
            {{- if .Values.global.documentStore.type.gcp.enabled }}
            - name: gcp-credentials-volume
              mountPath: {{ .Values.global.documentStore.type.gcp.mountPath | quote }}
              readOnly: true
            {{- end }}
            {{- if eq (include "camundaPlatform.hasCaBundle" .) "true" }}
            {{- include "camundaPlatform.caBundleVolumeMount" . | nindent 12 }}
            {{- include "camundaPlatform.caBundleTruststoreVolumeMount" . | nindent 12 }}
            {{- end }}
            {{- if (or .Values.camundaHub.restapi.extraVolumeMounts .Values.webModeler.restapi.extraVolumeMounts) }}
            {{- (or .Values.camundaHub.restapi.extraVolumeMounts .Values.webModeler.restapi.extraVolumeMounts) | toYaml | nindent 12 }}
            {{- end }}
        {{- if (or .Values.camundaHub.restapi.sidecars .Values.webModeler.restapi.sidecars) }}
        {{- (or .Values.camundaHub.restapi.sidecars .Values.webModeler.restapi.sidecars) | toYaml | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          {{- if and (or .Values.camundaHub.persistence.enabled .Values.webModeler.persistence.enabled) (or .Values.camundaHub.persistence.existingClaim .Values.webModeler.persistence.existingClaim) }}
          persistentVolumeClaim:
            claimName: {{ (or .Values.camundaHub.persistence.existingClaim .Values.webModeler.persistence.existingClaim) }}
          {{- else if (or .Values.camundaHub.persistence.enabled .Values.webModeler.persistence.enabled) }}
          ephemeral:
            volumeClaimTemplate:
              {{- with (or .Values.camundaHub.persistence.annotations .Values.webModeler.persistence.annotations) }}
              metadata:
                annotations: {{- toYaml . | nindent 18 }}
              {{- end }}
              spec:
                accessModes: {{ (or .Values.camundaHub.persistence.accessModes .Values.webModeler.persistence.accessModes) | default (list "ReadWriteOnce") | toYaml | nindent 18 }}
                {{- with (or .Values.camundaHub.persistence.storageClassName .Values.webModeler.persistence.storageClassName) }}
                storageClassName: {{ . | quote }}
                {{- end }}
                {{- with (or .Values.camundaHub.persistence.selector .Values.webModeler.persistence.selector) }}
                selector: {{- toYaml . | nindent 18 }}
                {{- end }}
                resources:
                  requests:
                    storage: {{ (or .Values.camundaHub.persistence.size .Values.webModeler.persistence.size) | default "1Gi" | quote }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: config
          configMap:
            name: {{ include "webModeler.fullname" . }}-restapi-configuration
        {{- if .Values.global.documentStore.type.gcp.enabled }}
        {{- include "camundaPlatform.emitVolumeFromSecretConfig" (dict
            "volumeName" "gcp-credentials-volume"
            "config" .Values.global.documentStore.type.gcp
            "fileName" .Values.global.documentStore.type.gcp.fileName
        ) | nindent 8 }}
        {{- end }}
        {{- if eq (include "camundaPlatform.hasCaBundle" .) "true" }}
        {{- include "camundaPlatform.caBundleVolume" . | nindent 8 }}
        {{- include "camundaPlatform.caBundleTruststoreVolume" . | nindent 8 }}
        {{- end }}
        {{- if (or .Values.camundaHub.restapi.extraVolumes .Values.webModeler.restapi.extraVolumes) }}
        {{- (or .Values.camundaHub.restapi.extraVolumes .Values.webModeler.restapi.extraVolumes) | toYaml | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "webModeler.serviceAccountName" . }}
      {{- if (or .Values.camundaHub.restapi.dnsConfig .Values.webModeler.restapi.dnsConfig) }}
      dnsConfig: {{- toYaml (or .Values.camundaHub.restapi.dnsConfig .Values.webModeler.restapi.dnsConfig) | nindent 8 }}
      {{- end }}
      {{- if (or .Values.camundaHub.restapi.dnsPolicy .Values.webModeler.restapi.dnsPolicy) }}
      dnsPolicy: {{ (or .Values.camundaHub.restapi.dnsPolicy .Values.webModeler.restapi.dnsPolicy) | quote }}
      {{- end }}
      {{- if (or .Values.camundaHub.restapi.podSecurityContext .Values.webModeler.restapi.podSecurityContext) }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" (or .Values.camundaHub.restapi.podSecurityContext .Values.webModeler.restapi.podSecurityContext) "context" $) | nindent 8 }}
      {{- end }}
      {{- with (or .Values.camundaHub.restapi.nodeSelector .Values.webModeler.restapi.nodeSelector) | default .Values.global.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with (or .Values.camundaHub.restapi.affinity .Values.webModeler.restapi.affinity) }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with (or .Values.camundaHub.restapi.tolerations .Values.webModeler.restapi.tolerations) }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
