{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
{{- $hub := include "camundaHub.values" . | fromYaml -}}
{{- $upgradePhase := include "camundaHub.upgradePhase" . -}}
{{- $deploymentStrategy := $hub.persistence.deploymentStrategy | default "RollingUpdate" -}}
{{- if not (has $deploymentStrategy (list "RollingUpdate" "Recreate")) -}}
{{- fail "webModeler.persistence.deploymentStrategy (or camundaHub.persistence.deploymentStrategy) value must be one of 'RollingUpdate', 'Recreate'" -}}
{{- end -}}
{{- if and (eq $deploymentStrategy "Recreate") (not $hub.persistence.enabled) -}}
{{- fail "webModeler.persistence.deploymentStrategy (or camundaHub.persistence.deploymentStrategy): Recreate requires persistence.enabled: true on the same values path. The default chart-managed path uses a per-pod ephemeral volume with no Multi-Attach contention, so Recreate is only useful when existingClaim points to a ReadWriteOnce volume; without persistence it only adds upgrade downtime" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webModeler.restapi.fullname" . }}
  labels: {{- include "webModeler.restapi.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  strategy:
    type: {{ $deploymentStrategy }}
  replicas: {{ ternary 0 (ternary 1 $hub.restapi.replicas (eq $upgradePhase "migrate")) (eq $upgradePhase "quiesce") }}
  selector:
    matchLabels: {{- include "webModeler.restapi.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "webModeler.restapi.labels" . | nindent 8 }}
        camunda.io/upgrade-phase: {{ $upgradePhase | quote }}
      {{- if $hub.restapi.podLabels }}
      {{- tpl (toYaml $hub.restapi.podLabels) $ | nindent 8 }}
      {{- end }}
      {{- if or (and (eq (include "camundaPlatform.hasCaBundle" .) "true") .Values.global.tls.caBundle.autoRollout) $hub.restapi.podAnnotations }}
      annotations:
        {{- with (include "camundaPlatform.caBundleChecksumAnnotation" .) }}{{ . | nindent 8 }}{{- end }}
        {{- with $hub.restapi.podAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      imagePullSecrets:
        {{- include "webModeler.imagePullSecrets" . | nindent 8 }}
      initContainers:
        {{- if eq (include "camundaPlatform.hasCaBundle" .) "true" }}
        {{- include "camundaPlatform.caBundleInitContainer" (dict "context" $ "image" (include "webModeler.restapi.image" $)) | nindent 8 }}
        {{- end }}
        {{- with $hub.restapi.initContainers }}
        {{- tpl (toYaml . | nindent 8) $ }}
        {{- end }}
      containers:
        - name: {{ include "webModeler.name" . }}-restapi
          image: {{ include "webModeler.restapi.image" . | quote }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if $hub.restapi.containerSecurityContext }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $hub.restapi.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "CAMUNDA_LICENSE_KEY"
                "config" .Values.global.license
            ) | nindent 12 }}
            - name: JAVA_OPTIONS
              value: {{ $hub.restapi.javaOpts | default "-XX:MaxRAMPercentage=80.0" | quote }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "SPRING_DATASOURCE_PASSWORD"
                "config" $hub.restapi.externalDatabase
            ) | nindent 12 }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "RESTAPI_MAIL_PASSWORD"
                "config" $hub.restapi.mail
            ) | nindent 12 }}
            - name: RESTAPI_PUSHER_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "webModeler.fullname" . }}-configuration
                  key: pusher-app-id
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "RESTAPI_PUSHER_KEY"
                "config" ($hub.restapi.pusher.client)
                "defaultSecretName" (include "webModeler.fullname" .)
                "defaultSecretKey" "pusher-app-key"
            ) | nindent 12 }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "RESTAPI_PUSHER_SECRET"
                "config" ($hub.restapi.pusher)
                "defaultSecretName" (include "webModeler.fullname" .)
                "defaultSecretKey" "pusher-app-secret"
            ) | nindent 12 }}
            - name: ZEEBE_CLIENT_CONFIG_PATH
              value: {{ $hub.restapi.zeebeClientConfigPath | default "/tmp/zeebe_client_cache.txt" | quote }}
            - name: CAMUNDA_MODELER_FEATURE_CONSOLE_ENABLED
              value: {{ include "camundaHub.consoleEnabled" . | quote }}
            - name: CAMUNDA_MODELER_FEATURE_GLOBAL_NAVIGATION_V2_ENABLED
              value: "false"
            {{- if and .Values.global.documentStore.type.aws.enabled (not .Values.global.documentStore.type.aws.irsa.enabled) }}
            - name: AWS_ACCESS_KEY_ID
              {{- include "camundaPlatform.emitAwsDocumentStoreSecret" (dict
                  "secretType" "accessKeyId"
                  "context" .
              ) | nindent 14 }}
            - name: AWS_SECRET_ACCESS_KEY
              {{- include "camundaPlatform.emitAwsDocumentStoreSecret" (dict
                  "secretType" "secretAccessKey"
                  "context" .
              ) | nindent 14 }}
            {{- end }}
            {{- if eq (lower .Values.global.documentStore.activeStoreId) "gcp" }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ printf "%s/%s" .Values.global.documentStore.type.gcp.mountPath .Values.global.documentStore.type.gcp.fileName | quote }}
            {{- end }}
          {{- if eq (include "camundaPlatform.hasCaBundle" .) "true" }}
            {{- include "camundaPlatform.caBundleEnv" . | nindent 12 }}
            {{- include "camundaPlatform.caBundleJavaToolOptionsEnv" . | nindent 12 }}
          {{- end }}
          {{- with $hub.restapi.env }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- $documentStoreEnvFrom := ne (include "camundaPlatform.extraConfigHasPath" (dict "extraConfiguration" $hub.restapi.extraConfiguration "path" (list "camunda" "document"))) "true" }}
          {{- if or $documentStoreEnvFrom $hub.restapi.envFrom }}
          envFrom:
          {{- if $documentStoreEnvFrom }}
            - configMapRef:
                name: {{ include "camundaPlatform.fullname" . }}-documentstore-env-vars
          {{- end }}
          {{- if $hub.restapi.envFrom }}
            {{- $hub.restapi.envFrom | toYaml | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if $hub.restapi.command }}
          command: {{ toYaml $hub.restapi.command | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml $hub.restapi.resources | nindent 12 }}
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
            - containerPort: 8091
              name: http-management
              protocol: TCP
          {{- if $hub.restapi.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ include "camundaPlatform.joinpath" (list $hub.contextPath $hub.restapi.startupProbe.probePath) }}
              scheme: {{ $hub.restapi.startupProbe.scheme }}
              port: http-management
            initialDelaySeconds: {{ $hub.restapi.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ $hub.restapi.startupProbe.periodSeconds }}
            successThreshold: {{ $hub.restapi.startupProbe.successThreshold }}
            failureThreshold: {{ $hub.restapi.startupProbe.failureThreshold }}
            timeoutSeconds: {{ $hub.restapi.startupProbe.timeoutSeconds }}
          {{- end }}
          {{- if $hub.restapi.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ include "camundaPlatform.joinpath" (list $hub.contextPath $hub.restapi.readinessProbe.probePath) }}
              scheme: {{ $hub.restapi.readinessProbe.scheme }}
              port: http-management
            initialDelaySeconds: {{ $hub.restapi.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $hub.restapi.readinessProbe.periodSeconds }}
            successThreshold: {{ $hub.restapi.readinessProbe.successThreshold }}
            failureThreshold: {{ $hub.restapi.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ $hub.restapi.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if $hub.restapi.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ include "camundaPlatform.joinpath" (list $hub.contextPath $hub.restapi.livenessProbe.probePath) }}
              scheme: {{ $hub.restapi.livenessProbe.scheme }}
              port: http-management
            initialDelaySeconds: {{ $hub.restapi.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $hub.restapi.livenessProbe.periodSeconds }}
            successThreshold: {{ $hub.restapi.livenessProbe.successThreshold }}
            failureThreshold: {{ $hub.restapi.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ $hub.restapi.livenessProbe.timeoutSeconds }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /home/runner/config/application.yaml
              subPath: application.yaml
          {{- with $hub.restapi.extraConfiguration }}
          {{- include "camundaPlatform.extraConfigurationVolumeMounts" (dict "extraConfig" . "volumeName" "config" "basePath" "/home/runner/config") | trim | nindent 12 }}
          {{- end }}
            {{- if .Values.global.documentStore.type.gcp.enabled }}
            - name: gcp-credentials-volume
              mountPath: {{ .Values.global.documentStore.type.gcp.mountPath | quote }}
              readOnly: true
            {{- end }}
            {{- if eq (include "camundaPlatform.hasCaBundle" .) "true" }}
            {{- include "camundaPlatform.caBundleVolumeMount" . | nindent 12 }}
            {{- include "camundaPlatform.caBundleTruststoreVolumeMount" . | nindent 12 }}
            {{- end }}
            {{- if $hub.restapi.extraVolumeMounts }}
            {{- $hub.restapi.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
        {{- if $hub.restapi.sidecars }}
        {{- $hub.restapi.sidecars | toYaml | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          {{- if and $hub.persistence.enabled $hub.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ $hub.persistence.existingClaim }}
          {{- else if $hub.persistence.enabled }}
          ephemeral:
            volumeClaimTemplate:
              {{- with $hub.persistence.annotations }}
              metadata:
                annotations: {{- toYaml . | nindent 18 }}
              {{- end }}
              spec:
                accessModes: {{ $hub.persistence.accessModes | default (list "ReadWriteOnce") | toYaml | nindent 18 }}
                {{- with $hub.persistence.storageClassName }}
                storageClassName: {{ . | quote }}
                {{- end }}
                {{- with $hub.persistence.selector }}
                selector: {{- toYaml . | nindent 18 }}
                {{- end }}
                resources:
                  requests:
                    storage: {{ $hub.persistence.size | default "1Gi" | quote }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: config
          configMap:
            name: {{ include "webModeler.fullname" . }}-restapi-configuration
        {{- if .Values.global.documentStore.type.gcp.enabled }}
        {{- include "camundaPlatform.emitVolumeFromSecretConfig" (dict
            "volumeName" "gcp-credentials-volume"
            "config" .Values.global.documentStore.type.gcp
            "fileName" .Values.global.documentStore.type.gcp.fileName
        ) | nindent 8 }}
        {{- end }}
        {{- if eq (include "camundaPlatform.hasCaBundle" .) "true" }}
        {{- include "camundaPlatform.caBundleVolume" . | nindent 8 }}
        {{- include "camundaPlatform.caBundleTruststoreVolume" . | nindent 8 }}
        {{- end }}
        {{- if $hub.restapi.extraVolumes }}
        {{- $hub.restapi.extraVolumes | toYaml | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "webModeler.serviceAccountName" . }}
      {{- if kindIs "bool" $hub.automountServiceAccountToken }}
      automountServiceAccountToken: {{ $hub.automountServiceAccountToken }}
      {{- end }}
      {{- if $hub.restapi.dnsConfig }}
      dnsConfig: {{- toYaml $hub.restapi.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if $hub.restapi.dnsPolicy }}
      dnsPolicy: {{ $hub.restapi.dnsPolicy | quote }}
      {{- end }}
      {{- if $hub.restapi.podSecurityContext }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $hub.restapi.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- with $hub.restapi.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $hub.restapi.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $hub.restapi.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
