{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
{{- $wmVals := include "camundaHub.webModelerValues" . | fromYaml -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webModeler.restapi.fullname" . }}
  labels: {{- include "webModeler.restapi.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ $wmVals.restapi.replicas }}
  selector:
    matchLabels: {{- include "webModeler.restapi.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "webModeler.restapi.labels" . | nindent 8 }}
      {{- if $wmVals.restapi.podLabels }}
      {{- tpl (toYaml $wmVals.restapi.podLabels) $ | nindent 8 }}
      {{- end }}
      {{- if $wmVals.restapi.podAnnotations }}
      annotations:
        {{- tpl (toYaml $wmVals.restapi.podAnnotations) $ | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        {{- include "webModeler.imagePullSecrets" . | nindent 8 }}
      initContainers:
        {{- tpl ($wmVals.restapi.initContainers | default list | toYaml | nindent 8) $ }}
      containers:
        - name: {{ include "webModeler.name" . }}-restapi
          image: {{ include "webModeler.restapi.image" . | quote }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if $wmVals.restapi.containerSecurityContext }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $wmVals.restapi.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "CAMUNDA_LICENSE_KEY"
                "config" .Values.global.license
            ) | nindent 12 }}
            - name: JAVA_OPTIONS
              value: {{ $wmVals.restapi.javaOpts | default "-XX:MaxRAMPercentage=80.0" | quote }}
            {{- if not .Values.webModelerPostgresql.enabled }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "SPRING_DATASOURCE_PASSWORD"
                "config" $wmVals.restapi.externalDatabase
            ) | nindent 12 }}
            {{- else }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.webModelerPostgresql.auth.existingSecret }}
                  key: {{ .Values.webModelerPostgresql.auth.secretKeys.userPasswordKey }}
            {{- end }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "RESTAPI_MAIL_PASSWORD"
                "config" $wmVals.restapi.mail
            ) | nindent 12 }}
            - name: RESTAPI_PUSHER_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "webModeler.fullname" . }}-configuration
                  key: pusher-app-id
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "RESTAPI_PUSHER_KEY"
                "config" $wmVals.restapi.pusher.client
                "defaultSecretName" (include "webModeler.fullname" .)
                "defaultSecretKey" "pusher-app-key"
            ) | nindent 12 }}
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "RESTAPI_PUSHER_SECRET"
                "config" $wmVals.restapi.pusher
                "defaultSecretName" (include "webModeler.fullname" .)
                "defaultSecretKey" "pusher-app-secret"
            ) | nindent 12 }}
            - name: ZEEBE_CLIENT_CONFIG_PATH
              value: {{ $wmVals.restapi.zeebeClientConfigPath | default "/tmp/zeebe_client_cache.txt" | quote }}
            {{- if and .Values.global.documentStore.type.aws.enabled (not .Values.global.documentStore.type.aws.irsa.enabled) }}
            - name: AWS_ACCESS_KEY_ID
              {{- include "camundaPlatform.emitAwsDocumentStoreSecret" (dict
                  "secretType" "accessKeyId"
                  "context" .
              ) | nindent 14 }}
            - name: AWS_SECRET_ACCESS_KEY
              {{- include "camundaPlatform.emitAwsDocumentStoreSecret" (dict
                  "secretType" "secretAccessKey"
                  "context" .
              ) | nindent 14 }}
            {{- end }}
            {{- if eq (lower .Values.global.documentStore.activeStoreId) "gcp" }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ printf "%s/%s" .Values.global.documentStore.type.gcp.mountPath .Values.global.documentStore.type.gcp.fileName | quote }}
            {{- end }}
          {{- with $wmVals.restapi.env }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "camundaPlatform.fullname" . }}-documentstore-env-vars
          {{- if $wmVals.restapi.envFrom }}
            {{- $wmVals.restapi.envFrom | toYaml | nindent 12 }}
          {{- end }}
          {{- if $wmVals.restapi.command }}
          command: {{ toYaml $wmVals.restapi.command | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml $wmVals.restapi.resources | nindent 12 }}
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
            - containerPort: 8091
              name: http-management
              protocol: TCP
          {{- if $wmVals.restapi.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ include "camundaPlatform.joinpath" (list $wmVals.contextPath $wmVals.restapi.startupProbe.probePath) }}
              scheme: {{ $wmVals.restapi.startupProbe.scheme }}
              port: http-management
            initialDelaySeconds: {{ $wmVals.restapi.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ $wmVals.restapi.startupProbe.periodSeconds }}
            successThreshold: {{ $wmVals.restapi.startupProbe.successThreshold }}
            failureThreshold: {{ $wmVals.restapi.startupProbe.failureThreshold }}
            timeoutSeconds: {{ $wmVals.restapi.startupProbe.timeoutSeconds }}
          {{- end }}
          {{- if $wmVals.restapi.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ include "camundaPlatform.joinpath" (list $wmVals.contextPath $wmVals.restapi.readinessProbe.probePath) }}
              scheme: {{ $wmVals.restapi.readinessProbe.scheme }}
              port: http-management
            initialDelaySeconds: {{ $wmVals.restapi.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $wmVals.restapi.readinessProbe.periodSeconds }}
            successThreshold: {{ $wmVals.restapi.readinessProbe.successThreshold }}
            failureThreshold: {{ $wmVals.restapi.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ $wmVals.restapi.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if $wmVals.restapi.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ include "camundaPlatform.joinpath" (list $wmVals.contextPath $wmVals.restapi.livenessProbe.probePath) }}
              scheme: {{ $wmVals.restapi.livenessProbe.scheme }}
              port: http-management
            initialDelaySeconds: {{ $wmVals.restapi.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $wmVals.restapi.livenessProbe.periodSeconds }}
            successThreshold: {{ $wmVals.restapi.livenessProbe.successThreshold }}
            failureThreshold: {{ $wmVals.restapi.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ $wmVals.restapi.livenessProbe.timeoutSeconds }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /home/runner/config/application.yaml
              subPath: application.yaml
          {{- with $wmVals.restapi.extraConfiguration }}
          {{- include "camundaPlatform.extraConfigurationVolumeMounts" (dict "extraConfig" . "volumeName" "config" "basePath" "/home/runner/config") | trim | nindent 12 }}
          {{- end }}
            {{- if .Values.global.documentStore.type.gcp.enabled }}
            - name: gcp-credentials-volume
              mountPath: {{ .Values.global.documentStore.type.gcp.mountPath | quote }}
              readOnly: true
            {{- end }}
            {{- if $wmVals.restapi.extraVolumeMounts }}
            {{- $wmVals.restapi.extraVolumeMounts | toYaml | nindent 12 }}
            {{- end }}
        {{- if $wmVals.restapi.sidecars }}
        {{- $wmVals.restapi.sidecars | toYaml | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          {{- if and $wmVals.persistence.enabled $wmVals.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ $wmVals.persistence.existingClaim }}
          {{- else if $wmVals.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "camundaPlatform.fullname" . }}-webModeler-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: config
          configMap:
            name: {{ include "webModeler.fullname" . }}-restapi-configuration
        {{- if .Values.global.documentStore.type.gcp.enabled }}
        {{- include "camundaPlatform.emitVolumeFromSecretConfig" (dict
            "volumeName" "gcp-credentials-volume"
            "config" .Values.global.documentStore.type.gcp
            "fileName" .Values.global.documentStore.type.gcp.fileName
        ) | nindent 8 }}
        {{- end }}
        {{- if $wmVals.restapi.extraVolumes }}
        {{- $wmVals.restapi.extraVolumes | toYaml | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "webModeler.serviceAccountName" . }}
      {{- if $wmVals.restapi.dnsConfig }}
      dnsConfig: {{- toYaml $wmVals.restapi.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if $wmVals.restapi.dnsPolicy }}
      dnsPolicy: {{ $wmVals.restapi.dnsPolicy | quote }}
      {{- end }}
      {{- if $wmVals.restapi.podSecurityContext }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $wmVals.restapi.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- with $wmVals.restapi.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $wmVals.restapi.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $wmVals.restapi.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
