{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webModeler.websockets.fullname" . }}
  labels:
    {{- include "webModeler.websockets.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.annotations}}
      {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if (or .Values.camundaHub.webModeler.websockets.service.annotations .Values.webModeler.websockets.service.annotations)}}
      {{- toYaml (or .Values.camundaHub.webModeler.websockets.service.annotations .Values.webModeler.websockets.service.annotations) | nindent 4 }}
    {{- end }}
spec:
  type: {{ (or .Values.camundaHub.webModeler.websockets.service.type .Values.webModeler.websockets.service.type) }}
  ports:
    - port: {{ (or .Values.camundaHub.webModeler.websockets.service.port .Values.webModeler.websockets.service.port) }}
      name: http
      targetPort: 8060
      protocol: TCP
  selector:
    {{- include "webModeler.websockets.matchLabels" . | nindent 4 }}
{{- end }}
