{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
{{- $wmVals := include "camundaHub.webModelerValues" . | fromYaml -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webModeler.websockets.fullname" . }}
  labels:
    {{- include "webModeler.websockets.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.annotations}}
      {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if $wmVals.websockets.service.annotations}}
      {{- toYaml $wmVals.websockets.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ $wmVals.websockets.service.type }}
  ports:
    - port: {{ $wmVals.websockets.service.port }}
      name: http
      targetPort: 8060
      protocol: TCP
  selector:
    {{- include "webModeler.websockets.matchLabels" . | nindent 4 }}
{{- end }}
