{{- if eq (include "camundaHub.webModelerEnabled" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webModeler.restapi.fullname" . }}
  labels:
    {{- include "webModeler.restapi.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.annotations}}
      {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if (dig "webModeler" "restapi" "service" "annotations" .Values.webModeler.restapi.service.annotations .Values.camundaHub)}}
      {{- toYaml (dig "webModeler" "restapi" "service" "annotations" .Values.webModeler.restapi.service.annotations .Values.camundaHub) | nindent 4 }}
    {{- end }}
spec:
  type: {{ (dig "webModeler" "restapi" "service" "type" .Values.webModeler.restapi.service.type .Values.camundaHub) }}
  ports:
    - port: {{ (dig "webModeler" "restapi" "service" "port" .Values.webModeler.restapi.service.port .Values.camundaHub) }}
      name: http
      targetPort: 8081
      protocol: TCP
    - port: {{ (dig "webModeler" "restapi" "service" "managementPort" .Values.webModeler.restapi.service.managementPort .Values.camundaHub) }}
      name: http-management
      targetPort: 8091
      protocol: TCP
  selector:
    {{- include "webModeler.restapi.matchLabels" . | nindent 4 }}
{{- end }}
