{{- if and (eq (include "camundaHub.webModelerEnabled" .) "true") .Values.webModeler.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webModeler.serviceAccountName" . }}
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  {{- with (dig "webModeler" "serviceAccount" "annotations" .Values.webModeler.serviceAccount.annotations .Values.camundaHub) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ dig "webModeler" "serviceAccount" "automountServiceAccountToken" .Values.webModeler.serviceAccount.automountServiceAccountToken .Values.camundaHub }}
{{- end }}
