{{- if and (eq (include "camundaHub.webModelerEnabled" .) "true") .Values.webModeler.serviceAccount.enabled -}}
{{- $wmVals := include "camundaHub.webModelerValues" . | fromYaml -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webModeler.serviceAccountName" . }}
  labels: {{- include "webModeler.labels" . | nindent 4 }}
  {{- with $wmVals.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $wmVals.serviceAccount.automountServiceAccountToken }}
{{- end }}
