# Basic test for maintenance Camunda 8 Helm charts.
name: "Test - nightly integration testing"

on:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  init:
    name: Nightly - Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-nightly-workflow-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Generate workflow matrix
        id: generate-nightly-workflow-matrix
        env:
          CI_NIGHTLY_MATRIX_FILE: ".github/config/integration-testing-scenarios/multitenancy.yaml"
        run: |
          cat ${CI_NIGHTLY_MATRIX_FILE} | envsubst | tee /tmp/matrix.yaml
          # Read matrix YAML file.
          matrix="$(yq '.matrix' --indent=0 --output-format json /tmp/matrix.yaml)"
          # Print and set matrix JSON object as an output.
          echo "${matrix}" | jq
          echo "matrix=$(echo ${matrix} | jq -c)" > "$GITHUB_OUTPUT"
  read-values:
    needs: init
    runs-on: ubuntu-latest
    outputs:
      values-content: ${{ steps.cat-file.outputs.values_content }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.init.outputs.matrix) }}
    permissions:
      contents: read
      id-token: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: camunda/camunda-platform-helm
      - name: Read Values File
        id: cat-file
        env:
          CHART_VERSION: ${{ matrix.version }}
          SCENARIO_FILE: ${{ matrix.scenario-file }}
        run: |
          set -euo pipefail
          echo "values_content<<EOF" >> $GITHUB_OUTPUT
          cat charts/camunda-platform-${CHART_VERSION}/test/integration/scenarios/extra-scenarios/${SCENARIO_FILE} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - uses: cloudposse/github-action-matrix-outputs-write@ed06cf3a6bf23b8dce36d1cf0d63123885bb8375 # v1
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.version }}
          outputs: |-
            values_content: ${{ toJson(steps.cat-file.outputs.values_content) }}

  access-info:
    name: Read values files from matrix
    runs-on: ubuntu-latest
    needs: read-values
    outputs:
      result: ${{ steps.read.outputs.result }}
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@33cac12fa9282a7230a418d859b93fdbc4f27b5a # v1
        id: read
        with:
          matrix-step-name: read-values

  integration:
    if: ${{ needs.init.outputs.matrix != '[]' }}
    name: Integration Test - Camunda ${{ matrix.version }}
    needs: [init, read-values, access-info]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.init.outputs.matrix) }}
    permissions:
      contents: read
      id-token: write
      deployments: write
    secrets: inherit
    uses: ./.github/workflows/test-integration-template.yaml
    with:
      identifier: "${{ matrix.scenario-file }}-intg-${{ matrix.version }}"
      deployment-ttl: 1d
      platforms: "gke"
      flows: "install,upgrade"
      camunda-helm-dir: "camunda-platform-${{ matrix.version }}"
      #not sure what to pu as the git-ref since this will be a cron job and not a PR
      camunda-helm-git-ref: "${{ github.event.pull_request.head.sha }}"
      caller-git-ref: "${{ github.event.pull_request.head.sha }}"
      github-workflow-rerun-enabled: false
      extra-values: |
        ${{ fromJson(needs.access-info.outputs.result).values_content[matrix.version] }}
  failure:
    runs-on: ubuntu-latest
    needs: [integration]
    if: failure()
    continue-on-error: true
    steps:
      - name: Get integration testing scneario
        id: get-scneario
        env:
          CI_NIGHTLY_MATRIX_FILE: ".github/config/integration-testing-scenarios/multitenancy.yaml"
        run: |
          filename="${CI_NIGHTLY_MATRIX_FILE##*/}"
          echo CI_NIGHTLY_MATRIX_FILE="${filename%%.*}" >> "$GITHUB_ENV"

      - name: Notify in Slack in case of failure
        id: slack-notification
        uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "unfurl_links": false,
              "unfurl_media": false,
              "text": "${{ github.event.repository.name }} (${{ github.server_url }}/${{ github.repository }}) scheduled workflow: ${{ github.workflow }} failed for ${{ env.CI_NIGHTLY_MATRIX_FILE }}! Please check: ${{ env.WORKFLOW_URL }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":automation-platform-failure: :mechanic: <${{ github.server_url }}/${{ github.repository }}|[${{ github.event.repository.name }}]> scheduled workflow: ${{ github.workflow }} failed for ${{ env.CI_NIGHTLY_MATRIX_FILE }}! \n :link: Please check: ${{ env.WORKFLOW_URL }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.DISTRO_CI_SLACK_BOT_TOKEN }}
          WORKFLOW_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  # test:
  #   if: ${{ needs.init.outputs.matrix != '[]' }}
  #   name: Camunda ${{ matrix.version }}
  #   needs: [init, read-values, access-info]
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       version: ${{ fromJson(needs.init.outputs.matrix) }}
  #   uses: ./.github/workflows/test-chart-version-template.yaml
  #   secrets: inherit
  #   with:
  #     chart-version: "${{ matrix.version }}"
  #     pr_number: "${{ github.event.pull_request.number }}" # Required as there is a github bug that prevent the concurrency group on the sub workflow getting the pull_request number from the github event
  #     identifier: "${{ matrix.scenario-file }}-intg-${{ matrix.version }}"
  #     extra-values: |
  #       ${{ fromJson(needs.access-info.outputs.result).values_content[matrix.version] }}
