# Basic test for maintenance Camunda 8 Helm charts.
name: "Test - Chart Version Nightly - Template"

on:
  workflow_call:
    inputs:
      camunda-version:
        description: Camunda version to test
        required: true
        type: string
      case:
        description: Type
        required: true
        type: string
      scenario:
        description: Scenario
        required: true
        type: string
      auth:
        description: Scenario
        required: true
        type: string
      exclude:
        description: Scenario
        required: true
        type: string
      values-enterprise:
        description: Enable enterprise values
        required: false
        default: "false"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.scenario }}-${{ inputs.camunda-version }}-${{ inputs.auth }}-${{ inputs.exclude }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  validation:
    name: Camunda ${{ inputs.camunda-version }} - Validation
    uses: ./.github/workflows/chart-validate-template.yaml
    with:
      identifier: "${{ inputs.case }}-${{ inputs.scenario }}-vald-${{ inputs.camunda-version }}-${{ inputs.auth }}-${{ inputs.exclude }}"
      camunda-helm-dir: "camunda-platform-${{ inputs.camunda-version }}"
      camunda-helm-git-ref: "${{ github.event.pull_request.head.sha }}"

  integration:
    name: Camunda ${{ inputs.camunda-version }} - ${{ matrix.scenario }}
    needs: validation
    permissions:
      contents: read
      id-token: write
      deployments: write
      packages: read
    secrets: inherit
    uses: ./.github/workflows/test-integration-template.yaml
    with:
      identifier: "${{ inputs.camunda-version }}"
      platforms: "gke"
      flows: "install,upgrade-patch,upgrade-minor"
      camunda-helm-dir: "camunda-platform-${{ inputs.camunda-version }}"
      test-case: "${{ inputs.case }}"
      scenario: "${{ inputs.scenario }}"
      auth: "${{ inputs.auth }}"
      exclude: "${{ inputs.exclude }}"
      values-enterprise: "${{ inputs.values-enterprise }}"
      values-digest: "true"
      camunda-helm-git-ref: "${{ github.event.pull_request.head.sha }}"
      vault-secret-mapping: |
        secret/data/products/distribution/ci ENTRA_APP_CLIENT_ID;
        secret/data/products/distribution/ci ENTRA_APP_CLIENT_SECRET;
        secret/data/products/distribution/ci ENTRA_APP_DIRECTORY_ID;
        secret/data/products/distribution/ci ENTRA_APP_OBJECT_ID;
        secret/data/products/distribution/ci DISTRO_QA_E2E_TESTS_KEYCLOAK_CLIENTS_SECRET;
        secret/data/products/qa/ci/s3 access_key_id | IDP_AWS_ACCESSKEY;
        secret/data/products/qa/ci/s3 bucket_name | IDP_AWS_BUCKET_NAME;
        secret/data/products/qa/ci/s3 bucket_region | IDP_AWS_REGION;
        secret/data/products/qa/ci/s3 secret_access_key | IDP_AWS_SECRETKEY;
