name: "Test - Local Cluster - Template"

on:
  workflow_call:
    inputs:
      identifier:
        description: The unique identifier of used in the deployment.
        required: true
        type: string
      camunda-helm-git-ref:
        required: false
        default: main
        type: string
      camunda-helm-dir:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.identifier }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  local:
    name: Local cluster - KIND
    # This job needs to run on self-hosted runners because it requires more resources
    # than the default GitHub runners provide.
    runs-on: gcp-core-8-release
    env:
      TEST_NAMESPACE: camunda-platform
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: "${{ inputs.camunda-helm-git-ref }}"
      - name: Import Vault secrets
        id: test-credentials-secret
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/distribution/ci DOCKERHUB_USERNAME | TEST_DOCKER_USERNAME;
            secret/data/products/distribution/ci DOCKERHUB_PASSWORD | TEST_DOCKER_PASSWORD;
          exportEnv: true
      - name: Install common software tooling
        uses: camunda/infra-global-github-actions/common-tooling@b20a0e8f64ea6554900bab2d3fb3906be613aa19 # main
        with:
          overwrite: "false"
          build-essential-enabled: "true"
          node-enabled: "false"
          yarn-enabled: "false"
          buildx-enabled: "false"
          java-enabled: "false"
          python-enabled: "false"
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential gawk make
      - name: Install tools
        uses: ./.github/actions/install-tool-versions
        with:
          tools: |
            helm
            kind
            kubectl
            task
      - name: Docker Hub login
        run: |
          echo "${TEST_DOCKER_PASSWORD}" | docker login -u "${TEST_DOCKER_USERNAME}" --password-stdin
      - name: CI Setup - Set test type vars
        uses: ./.github/actions/test-type-vars
        with:
          chart-dir: "${{ inputs.camunda-helm-dir }}"
          values-enterprise: false
          values-digest: true
      - name: Create KIND cluster
        run: |
          kind create cluster --name camunda-platform-local
          kubectl config use-context kind-camunda-platform-local
      # Login to Docker registry to avoid image pull rate limit.
      - name: Create Docker login secret
        env:
          TEST_CREATE_DOCKER_LOGIN_SECRET: "TRUE"
          TEST_DOCKER_USERNAME: ${{ env.TEST_DOCKER_USERNAME }}
          TEST_DOCKER_PASSWORD: ${{ env.TEST_DOCKER_PASSWORD }}
        run: |
          kubectl create namespace ${{ env.TEST_NAMESPACE }}
          task docker-login --taskfile test/integration/scenarios/lib/init-seed-taskfile.yaml
      - name: Prepare Camunda Helm chart installation
        run: |
          make helm.repos-add
          helm package --dependency-update "charts/${{ inputs.camunda-helm-dir }}"
      - name: ⭐ Install Camunda Helm chart ⭐
        timeout-minutes: 10
        run: |
          test -n "${{ env.TEST_HELM_DIGEST_VALUES }}" &&
            TEST_HELM_EXTRA_ARGS="--values charts/${{ inputs.camunda-helm-dir }}/values-digest.yaml"
          helm install camunda-platform *.tgz --wait --timeout 10m0s \
            --namespace ${{ env.TEST_NAMESPACE }} \
            --values "charts/${{ inputs.camunda-helm-dir }}/test/integration/scenarios/common/values-integration-test-pull-secrets.yaml" \
            --values "charts/${{ inputs.camunda-helm-dir }}/values-local.yaml" \
            ${TEST_HELM_EXTRA_ARGS}
      - name: Get Pods
        if: failure()
        run: |
          kubectl get pods --namespace ${{ env.TEST_NAMESPACE }}
      - name: Debug - Get Pods info
        if: failure()
        run: |
          kubectl get pods --namespace ${{ env.TEST_NAMESPACE }} -o yaml
          kubectl describe pods --namespace ${{ env.TEST_NAMESPACE }}
