# Basic test for maintenance Camunda 8 Helm charts.
name: "Test - nightly integration testsing"

on:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  init:
    name: Nightly - Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-nightly-workflow-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Generate workflow matrix
        id: generate-nightly-workflow-matrix
        env:
          CI_NIGHTLY_MATRIX_FILE: ".github/config/integration-testing-scenarios/multitenancy.yaml"
        run: |
          cat ${CI_NIGHTLY_MATRIX_FILE} | envsubst | tee /tmp/matrix.yaml
          # Read matrix YAML file.
          matrix="$(yq '.matrix' --indent=0 --output-format json /tmp/matrix.yaml)"
          # Print and set matrix JSON object as an output.
          echo "${matrix}" | jq
          echo "matrix=$(echo ${matrix} | jq -c)" > "$GITHUB_OUTPUT"
  read-values:
    needs: init
    runs-on: ubuntu-latest
    outputs:
      values-content: ${{ steps.cat-file.outputs.values_content }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.init.outputs.matrix) }}
    permissions:
      contents: read
      id-token: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: camunda/camunda-platform-helm
      - name: Read Values File
        id: cat-file
        env:
          CHART_VERSION: ${{ matrix.version }}
          SCENARIO_FILE: ${{ matrix.scenario-file }}
        run: |
          set -euo pipefail
          cat charts/camunda-platform-${CHART_VERSION}/test/integration/scenarios/extra-scenarios/${SCENARIO_FILE} > values.yaml
          values_base64=$(base64 -w 0 values.yaml)
          echo "values_content=${values_base64}" >> "$GITHUB_OUTPUT"
      - uses: cloudposse/github-action-matrix-outputs-write@ed06cf3a6bf23b8dce36d1cf0d63123885bb8375 # v1
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.version }}
          outputs: |-
            values_content: ${{ steps.cat-file.outputs.values_content }}

  access-info:
    name: Read values files from matrix
    runs-on: ubuntu-latest
    needs: read-values
    outputs:
      result: ${{ steps.read.outputs.result }}
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@33cac12fa9282a7230a418d859b93fdbc4f27b5a # v1
        id: read
        with:
          matrix-step-name: read-values
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [init, access-info]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.init.outputs.matrix) }}
    steps:
      - name: testing
        run: |
          echo "${{ fromJson(needs.access-info.outputs.result).values_content[matrix.version] }}"| base64 --decode

  integration:
    if: ${{ needs.init.outputs.matrix != '[]' }}
    name: Integration Test - Camunda ${{ matrix.version }}
    needs: [init, read-values, access-info]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.init.outputs.matrix) }}
    permissions:
      contents: read
      id-token: write
      deployments: write
    secrets: inherit
    uses: ./.github/workflows/test-integration-template.yaml
    with:
      identifier: "${{ matrix.scenario-file }}-intg-${{ matrix.version }}"
      deployment-ttl: 1d
      platforms: "gke"
      flows: "install,upgrade"
      camunda-helm-dir: "camunda-platform-${{ matrix.version }}"
      #not sure what to pu as the git-ref since this will be a cron job and not a PR
      camunda-helm-git-ref: "${{ github.event.pull_request.head.sha }}"
      caller-git-ref: "${{ github.event.pull_request.head.sha }}"
      extra-values: |
        "${{ fromBase64(fromJson(needs.access-info.outputs.result).values_content[matrix.version]) }}"
