{{- if eq (include "camundaHub.consoleEnabled" .) "true" -}}
{{- $consoleVals := include "camundaHub.consoleValues" . | fromYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console.fullname" . }}-configuration
  labels:
    {{- include "console.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- if $consoleVals.configuration }}
      {{- include "common.tplvalues.render" ( dict "value" $consoleVals.configuration "context" $ ) | nindent 4 }}
    {{- else }}
    # https://docs.camunda.io/docs/self-managed/console-deployment/configuration/
    camunda:
      console:
        oAuth:
          {{- $consoleAuth := include "camundaHub.consoleAuthValues" . | fromYaml }}
          audience: {{ $consoleAuth.audience | quote }}
          clientId: {{ $consoleAuth.clientId | quote }}
          issuer: {{ include "camundaPlatform.authIssuerUrlWithFallback" . | quote }}
          jwksUri: {{ include "camundaPlatform.authIssuerBackendUrlEndpointCerts" . | quote }}
          type: {{ include "camundaPlatform.authIssuerType" . | quote }}
          wellKnown: {{ $consoleAuth.wellKnown | quote }}
        managed:
          method: plain
          releases:
            {{- include "camundaPlatform.releaseInfo" . | nindent 10 }}
    {{- end }}
  {{- if $consoleVals.extraConfiguration }}
  application-override.yaml: |
    {{- $merged := dict }}
    {{- range $consoleVals.extraConfiguration }}
    {{- $parsed := .content | fromYaml }}
    {{- $merged = mustMergeOverwrite $merged $parsed }}
    {{- end }}
    {{- $merged | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
