{{- if eq (include "camundaHub.consoleEnabled" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console.fullname" . }}-configuration
  labels:
    {{- include "console.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- if (or .Values.camundaHub.console.configuration .Values.console.configuration) }}
      {{- include "common.tplvalues.render" ( dict "value" (or .Values.camundaHub.console.configuration .Values.console.configuration) "context" $ ) | nindent 4 }}
    {{- else }}
    # https://docs.camunda.io/docs/self-managed/console-deployment/configuration/
    camunda:
      console:
        oAuth:
          audience: {{ (or .Values.global.identity.auth.camundaHub.console.audience .Values.global.identity.auth.console.audience) | quote }}
          clientId: {{ (or .Values.global.identity.auth.camundaHub.console.clientId .Values.global.identity.auth.console.clientId) | quote }}
          issuer: {{ include "camundaPlatform.authIssuerUrlWithFallback" . | quote }}
          jwksUri: {{ include "camundaPlatform.authIssuerBackendUrlEndpointCerts" . | quote }}
          type: {{ include "camundaPlatform.authIssuerType" . | quote }}
          wellKnown: {{ (or .Values.global.identity.auth.camundaHub.console.wellKnown .Values.global.identity.auth.console.wellKnown) | quote }}
        managed:
          method: plain
          releases:
            {{- include "camundaPlatform.releaseInfo" . | nindent 10 }}
    {{- end }}
  {{- if (or .Values.camundaHub.console.extraConfiguration .Values.console.extraConfiguration) }}
  application-override.yaml: |
    {{- $merged := dict }}
    {{- range (or .Values.camundaHub.console.extraConfiguration .Values.console.extraConfiguration) }}
    {{- $parsed := .content | fromYaml }}
    {{- $merged = mustMergeOverwrite $merged $parsed }}
    {{- end }}
    {{- $merged | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
