{{- if eq (include "camundaHub.consoleEnabled" .) "true" -}}
{{- $consoleVals := include "camundaHub.consoleValues" . | fromYaml -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ $consoleVals.replicas }}
  selector:
    matchLabels:
      {{- include "console.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/console/configmap.yaml") . | sha256sum }}
      {{- with $consoleVals.podAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "console.matchLabels" . | nindent 8 }}
        {{- if $consoleVals.podLabels }}
          {{- tpl (toYaml $consoleVals.podLabels) $ | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        {{- include "console.imagePullSecrets" . | nindent 8 }}
      initContainers:
        {{- tpl ($consoleVals.initContainers | default list | toYaml | nindent 8) $ }}
      serviceAccountName: {{ include "console.serviceAccountName" . }}
      {{- if $consoleVals.dnsConfig }}
      dnsConfig: {{- toYaml $consoleVals.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if $consoleVals.dnsPolicy }}
      dnsPolicy: {{ $consoleVals.dnsPolicy | quote }}
      {{- end }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $consoleVals.podSecurityContext "context" $) | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "camundaPlatform.imageByParams" (dict "base" .Values.global "overlay" $consoleVals) }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- if $consoleVals.containerSecurityContext }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" $consoleVals.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
                "envName" "CAMUNDA_LICENSE_KEY"
                "config" .Values.global.license
            ) | nindent 12 }}
            - name: NODE_EXTRA_CA_CERTS
              value: {{ printf "/usr/local/console/certificates/%s" $consoleVals.tls.certKeyFilename | quote }}
            - name: NODE_ENV
              value: {{ $consoleVals.nodeEnv | default "prod" | quote }}
            {{- if eq (include "camundaPlatform.authIssuerType" .) "KEYCLOAK"}}
            - name: KEYCLOAK_INTERNAL_BASE_URL
              value: {{ mustRegexReplaceAllLiteral "/realms/.+" (include "camundaPlatform.authIssuerBackendUrl" .) "" | quote }}
            - name: KEYCLOAK_BASE_URL
              value: {{ mustRegexReplaceAllLiteral "/realms/.+" (include "camundaPlatform.authIssuerUrlWithFallback" .) "" | quote }}
            - name: KEYCLOAK_REALM
              value: {{ $consoleVals.keycloak.realm | quote }}
            {{- end }}
            {{- $consoleAuth := include "camundaHub.consoleAuthValues" . | fromYaml }}
            - name: CAMUNDA_IDENTITY_AUDIENCE
              value: {{ $consoleAuth.audience | default "console-api" }}
            - name: CAMUNDA_IDENTITY_CLIENT_ID
              value: {{ $consoleAuth.clientId | default "console" }}
            - name: CAMUNDA_CONSOLE_CONTEXT_PATH
              value: {{ $consoleVals.contextPath | quote }}
            {{- if and .Values.global.documentStore.type.aws.enabled (not .Values.global.documentStore.type.aws.irsa.enabled) }}
            - name: AWS_ACCESS_KEY_ID
              {{- include "camundaPlatform.emitAwsDocumentStoreSecret" (dict
                  "secretType" "accessKeyId"
                  "context" .
              ) | nindent 14 }}
            - name: AWS_SECRET_ACCESS_KEY
              {{- include "camundaPlatform.emitAwsDocumentStoreSecret" (dict
                  "secretType" "secretAccessKey"
                  "context" .
              ) | nindent 14 }}
            {{- end }}
            {{- if eq (lower .Values.global.documentStore.activeStoreId) "gcp" }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ printf "%s/%s" .Values.global.documentStore.type.gcp.mountPath .Values.global.documentStore.type.gcp.fileName | quote }}
            {{- end }}
          {{- if $consoleVals.env}}
            {{ $consoleVals.env | toYaml | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "camundaPlatform.fullname" . }}-documentstore-env-vars
          {{- if $consoleVals.envFrom }}
            {{- $consoleVals.envFrom | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 9100
              protocol: TCP
          {{- if $consoleVals.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ $consoleVals.startupProbe.probePath }}
              scheme: {{ $consoleVals.startupProbe.scheme }}
              port: management
            initialDelaySeconds: {{ $consoleVals.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ $consoleVals.startupProbe.periodSeconds }}
            successThreshold: {{ $consoleVals.startupProbe.successThreshold }}
            failureThreshold: {{ $consoleVals.startupProbe.failureThreshold }}
            timeoutSeconds: {{ $consoleVals.startupProbe.timeoutSeconds }}
          {{- end }}
          {{- if $consoleVals.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $consoleVals.readinessProbe.probePath }}
              scheme: {{ $consoleVals.readinessProbe.scheme }}
              port: management
            initialDelaySeconds: {{ $consoleVals.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $consoleVals.readinessProbe.periodSeconds }}
            successThreshold: {{ $consoleVals.readinessProbe.successThreshold }}
            failureThreshold: {{ $consoleVals.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ $consoleVals.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if $consoleVals.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $consoleVals.livenessProbe.probePath }}
              scheme: {{ $consoleVals.livenessProbe.scheme }}
              port: management
            initialDelaySeconds: {{ $consoleVals.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $consoleVals.livenessProbe.periodSeconds }}
            successThreshold: {{ $consoleVals.livenessProbe.successThreshold }}
            failureThreshold: {{ $consoleVals.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ $consoleVals.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if $consoleVals.command}}
          command: {{ toYaml $consoleVals.command | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml $consoleVals.resources | nindent 12 }}
          volumeMounts:
            - name: console-configuration
              mountPath: /var/run/config
          {{- if $consoleVals.tls.enabled }}
            - name: console-certificates
              mountPath: /usr/local/console/certificates
              readOnly: true
          {{- end }}
            {{- if .Values.global.documentStore.type.gcp.enabled }}
            - name: gcp-credentials-volume
              mountPath: {{ .Values.global.documentStore.type.gcp.mountPath | quote }}
              readOnly: true
            {{- end }}
          {{- if $consoleVals.extraVolumeMounts }}
            {{- $consoleVals.extraVolumeMounts | toYaml | nindent 12 }}
          {{- end }}
      {{- if $consoleVals.sidecars }}
        {{- $consoleVals.sidecars | toYaml | nindent 8 }}
      {{- end }}
      volumes:
        - name: console-configuration
          configMap:
            name: {{ include "console.fullname" . }}-configuration
        {{- include "camundaPlatform.emitTlsVolumeFromSecretConfig" (dict
            "volumeName" "console-certificates"
            "config" $consoleVals.tls
        ) | nindent 8 }}
        {{- if .Values.global.documentStore.type.gcp.enabled }}
        {{- include "camundaPlatform.emitVolumeFromSecretConfig" (dict
            "volumeName" "gcp-credentials-volume"
            "config" .Values.global.documentStore.type.gcp
            "fileName" .Values.global.documentStore.type.gcp.fileName
        ) | nindent 8 }}
        {{- end }}
      {{- if $consoleVals.extraVolumes }}
        {{- $consoleVals.extraVolumes | toYaml | nindent 8 }}
      {{- end }}
      {{- with $consoleVals.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $consoleVals.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $consoleVals.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
