{{- if and (eq (include "camundaHub.consoleEnabled" .) "true") .Values.console.serviceAccount.enabled -}}
{{- $consoleVals := include "camundaHub.consoleValues" . | fromYaml -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "console.serviceAccountName" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
  {{- with $consoleVals.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $consoleVals.serviceAccount.automountServiceAccountToken }}
{{- end }}
