{{- if and (eq (include "camundaHub.consoleEnabled" .) "true") .Values.console.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "console.serviceAccountName" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
  {{- with (dig "console" "serviceAccount" "annotations" .Values.console.serviceAccount.annotations .Values.camundaHub) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ dig "console" "serviceAccount" "automountServiceAccountToken" .Values.console.serviceAccount.automountServiceAccountToken .Values.camundaHub }}
{{- end }}
