{{- if eq (include "camundaHub.consoleEnabled" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.annotations}}
      {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if (dig "console" "service" "annotations" .Values.console.service.annotations .Values.camundaHub) }}
      {{- toYaml (dig "console" "service" "annotations" .Values.console.service.annotations .Values.camundaHub) | nindent 4 }}
    {{- end }}
spec:
  type: {{ (dig "console" "service" "type" .Values.console.service.type .Values.camundaHub) }}
  ports:
    - port: {{ (dig "console" "service" "port" .Values.console.service.port .Values.camundaHub) }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ (dig "console" "service" "managementPort" .Values.console.service.managementPort .Values.camundaHub) }}
      name: management
      targetPort: management
      protocol: TCP
  selector:
    {{- include "console.matchLabels" . | nindent 4 }}
{{- end }}
