#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:3d8be0298a1221c3934c9016c08de5bdde9b5528673f1585565fa5b4930c6d09"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.9-SNAPSHOT
    digest: "sha256:4174a2c04cd886c33c82b8772ac0849a2caaaa9cbf12c481d165993cbbd59044"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.9-SNAPSHOT
    digest: "sha256:cc1a42588dc6c999cf49fc0f0aca35629ef624b1dbb3fc12f4161bfd35572201"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:f0dbeb8ad7076d940a6fbff8a46bc01573fa3078933ff1c67b906b29177b2bd0"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:872e655da60cbce5a4a666073f849c447c1daa2c0d1161167387d5bc32e3e41e"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.9-SNAPSHOT
    digest: "sha256:0917c12c341011d30d48bde9e7899a66e49d1260bcdc1d6fa54f9c5397504b02"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:f56105d9435845a6074e53ae0cf0ca8933bb64eaf7820ddaaba6eb8274957aee"
