#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9-SNAPSHOT
    digest: "sha256:3d8be0298a1221c3934c9016c08de5bdde9b5528673f1585565fa5b4930c6d09"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.9-SNAPSHOT
    digest: "sha256:291cdaa212c4f1896f93662de42200dace938cda8b294baeefb45ce9ca26211e"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.9-SNAPSHOT
    digest: "sha256:0a14fbdd2ca0d81f13fc380fd7b0879e2fb1db031791e75422972afbe03bef2a"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: SNAPSHOT
      digest: "sha256:11c8ede15061e1bbc0aa19146f4439853f0d544cee3f47d336a642e9827794f1"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: SNAPSHOT
      digest: "sha256:f8482e8ea2ad92bf864f6a458437089c5f71d6accb77ab6b566f0ed97f6c5657"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.9-SNAPSHOT
    digest: "sha256:1058ef7f10a0aed654637c9e6d884a3cc6e689f0c6807c0dbd3eff9ed7e634c0"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: SNAPSHOT
    digest: "sha256:03d2c0084f5bca05f3b339f54adcb6b1872c906d26694f47b4689627ac68b9b1"
