#
# Camunda - Digest
#

console:
  # https://hub.docker.com/r/camunda/console/tags
  image:
    repository: camunda/console
    tag: 8.9.120
    digest: "sha256:b5dc326dfe83d083931114b84f7e261bb8c71567a0e627d157ceced0378108e3"

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.9.14
    digest: "sha256:6db82f41c78fd344d0caf4bf1daeb53539cba31d8b2f3c4672b0101331573c19"

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.9.22
    digest: "sha256:fa51d51ab7ce48d41ad9b139de26ab6b4b788e4cd00d984cf2b4745bbf7018bd"

#
# Web Modeler
#

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi/tags
  restapi:
    image:
      repository: camunda/web-modeler-restapi
      tag: 8.9.10
      digest: "sha256:605a9eb75937c340f018986100103507ec13a120b5f952bad791797cbb1822d8"

  # https://hub.docker.com/r/camunda/web-modeler-websockets/tags
  websockets:
    image:
      repository: camunda/web-modeler-websockets
      tag: 8.9.10
      digest: "sha256:a95765025bb4ff3422a196e8d44a312440e832c57f060da60e97a1f477b16681"

#
# Orchestration Cluster
#

orchestration:
  # https://hub.docker.com/r/camunda/camunda/tags
  image:
    repository: camunda/camunda
    tag: 8.9.22
    digest: "sha256:1c418134ae5a6b551a0ef3429a279f70ad30076dcbb7090698a55aab09a9bd0e"

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.9.10
    digest: "sha256:08813804ed02ff6c5ee2f7ab8fd64d447e9e3d03b4da864a136000ec46eac287"
